/********************************************************************
filename: 	GenLayer.h
file path:	dev\client\Src\Blockman

version:	1
author:		ajohn
company:	supernano
date:		2016-11-11
*********************************************************************/
#ifndef __GEN_LAYER_HEADER__
#define __GEN_LAYER_HEADER__

#include "BM_TypeDef.h"
#include "BM_Container_def.h"

namespace BLOCKMAN
{

class BiomeGenBase;
class GenLayer;
typedef vector<GenLayer*>::type GenLayerArr;

class GenLayer : public ObjectAlloc
{
public:
	/** the first array item is a linked list of the bioms, the second is the zoom function, the third is the same as the first. */
	static GenLayerArr initializeAllBiomeGenerators(i64 seed, TERRAIN_TYPE type);

	GenLayer(i64 seed);
	virtual ~GenLayer();

	/** Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an argument).	*/
	void initWorldGenSeed(i64 seed);

	/** Initialize layer's current chunkSeed based on the local worldGenSeed and the (x,z) chunk coordinates. */
	void initChunkSeed(i64 seed1, i64 seed2);

	/** returns a LCG pseudo random number from [0, x). Args: int x */
	int nextInt(int threshold);

	/**
	* Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	* amounts, or biomeList[] indices based on the particular GenLayer subclass.
	*/
	virtual int* getInts(int areax, int areay, int areaw, int areah) = 0;

	void addRef() { m_refCount++; }
	int subRef() { m_refCount--; return m_refCount; }
	void setParent(GenLayer* p);

protected:
	/** seed from World#getWorldSeed that is used in the LCG prng */
	i64 m_genSeed = 0;

	/** parent GenLayer that was provided via the constructor */
	GenLayer* m_parent = nullptr;

	/** final part of the LCG prng that uses the chunk X, Z coords along with the other two seeds to generate pseudorandom numbers */
	i64 m_chunkSeed = 0;

	/** base seed to the LCG prng provided via the constructor */
	i64 m_baseSeed = 0;

	// need ++ when ref, need -- when delete.
	int m_refCount = 0;
};

class GenLayerIsland : public GenLayer
{
public:
	GenLayerIsland(i64 seed) : GenLayer(seed) { }

	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerFuzzyZoom : public GenLayer
{
public:
	GenLayerFuzzyZoom(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
	
protected:
	int choose(int i0, int i1) { return nextInt(2) == 0 ? i0 : i1; }
	int choose(int i0, int i1, int i2, int i3);
};

class GenLayerAddIsland : public GenLayer
{
public:
	GenLayerAddIsland(i64 seed, GenLayer* parent);

	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerZoom : public GenLayer
{
public:
	GenLayerZoom(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
	/** Magnify a layer. Parms are seed adjustment, layer, number of times to magnify */
	static GenLayer* magnify(i64 seed, GenLayer* pLayer, int count);

protected:
	/** Chooses one of the two inputs randomly. */
	int choose(int i0, int i1) { return nextInt(2) == 0 ? i0 : i1; }

	/** returns the mode (most frequently occuring number) or a random number from the 4 integers provided */
	int modeOrRandom(int i0, int i1, int i2, int i3);	
};

class GenLayerAddSnow : public GenLayer
{
public:
	GenLayerAddSnow(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerAddMushroomIsland : public GenLayer
{
public:
	GenLayerAddMushroomIsland(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerRiverInit : public GenLayer
{
public:
	GenLayerRiverInit(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerRiver : public GenLayer
{
public:
	GenLayerRiver(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerSmooth : public GenLayer
{
public:
	GenLayerSmooth(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerBiome : public GenLayer
{
public:
	GenLayerBiome(i64 seed, GenLayer* parent, TERRAIN_TYPE type);

	int* getInts(int areax, int areay, int areaw, int areah);

protected:
	BiomeGenArr m_allowedBiomes;
};

class GenLayerHills : public GenLayer
{
public:
	GenLayerHills(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerShore : public GenLayer
{
public:
	GenLayerShore(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerSwampRivers : public GenLayer
{
public:
	GenLayerSwampRivers(i64 seed, GenLayer* parent);

	int* getInts(int areax, int areay, int areaw, int areah);
};

class GenLayerRiverMix : public GenLayer
{
public:
	GenLayerRiverMix(i64 seed, GenLayer* parent1, GenLayer* parent2);
	virtual ~GenLayerRiverMix();

	void initWorldGenSeed(i64 seed);
	int* getInts(int areax, int areay, int areaw, int areah);

protected:
	GenLayer* m_pBiomePatternGeneratorChain;
	GenLayer* m_pRiverPatternGeneratorChain;
};

class GenLayerVoronoiZoom : public GenLayer
{
public:
	GenLayerVoronoiZoom(i64 seed, GenLayer* parent);
	int* getInts(int areax, int areay, int areaw, int areah);
};


}
#endif