#pragma once
namespace BLOCKMAN {
	enum class TipType
	{
		VEHICLE_TIP,
		OTHER_TIP,
		GO_APP_SHOP,
		GO_NPC_MERCHANT,
		CHANGE_ACTORT_TIP,
		REVIVE,
		PICK_UP_ITEM,
		GET_MANOR,
		SELL_MANOR,
		SURE_SELL_MANOR,
		LACK_OF_PLATFORM_MONEY,
		UPGRADE_RESOURCE,
		CUSTOM_TIP,
		MANOR_BUILD_HOUSE,
		BUILD_WAR_GUESS_TIP,
		UNLOCK_COMMODITY,
		CONSUME_COIN_TIP,
		RANCHERS_EXPLORE_BEGIN,
		RANCHERS_TASK_FINISH,
		KEEP_ITEM,
		ENCHANTMENT_QUICK,
		PIXEL_GUNHALL_LOCK_MAP_DIAMOND,
		PIXEL_GUNHALL_LOCK_MODE,
		PIXEL_GUNHALL_MODE_NOT_OPEN,
	};

	enum class RanchTipType 
	{
		COMMON,
		UNLOCK_ITEMS,
		LACK_MATERIALS,
		BUILD_QUEUE_UNLOCK,
		GO_APP_SHOP,
		BACK_APP,
		LACK_ITEMS,
		ORDER_OPERATE_LOCK_ITEMS,
		LOCK_ITEMS_BY_BUILD_OPERATION,
		RANCH_STORAGE_FULL,
		LOCK_ITEMS_BY_UPGRADE_STORAGE,
		LOCK_ITEMS_BY_ORDER_HELP,
	};

	enum class BirdTipType 
	{
		COMMON,
		GO_APP_SHOP,
		BACK_APP,
		BIRD_UNLOCK_NEST,
		BIRD_EXPAND_CARRY,
		BIRD_EXPAND_CAPACITY,
		BIRD_LOTTERY,
		BIRD_OPEN_CHEST,
		BIRD_DELETE,
		BIRD_CARRY_FULL,
		BIRD_CAPACITY_FULL,
		BIRD_BUY_PERMISSIO,
	};
}