#pragma once
#include "Core.h"
#include "Math/IntMath.h"
#include "LuaRegister/Template/LuaRegister.h"
#include "Log/Log.h"
#include "World/Shop.h"
#include "Item/ItemStack.h"
#include "Util/AboutShopping.h"
#include "World/Manor.h"
#include "Setting/GunSetting.h"
#include "Setting/MonsterSetting.h"
#include "Setting/SkillSetting.h"

using namespace LORD;
using namespace BLOCKMAN;
using namespace LUA_REGISTER;

_BEGIN_REGISTER_CLASS(Vector3i)
_CLASSREGISTER_AddCtor()// new
_CLASSREGISTER_AddCtor(int, int, int)// new1
_CLASSREGISTER_AddVar(x, Vector3i::x)
_CLASSREGISTER_AddVar(y, Vector3i::y)
_CLASSREGISTER_AddVar(z, Vector3i::z)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(Vector3)
_CLASSREGISTER_AddCtor()// new
_CLASSREGISTER_AddCtor(float, float, float)// new1
_CLASSREGISTER_AddVar(x, Vector3::x)
_CLASSREGISTER_AddVar(y, Vector3::y)
_CLASSREGISTER_AddVar(z, Vector3::z)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(Goods)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, Goods::itemId)
_CLASSREGISTER_AddVar(itemMeta, Goods::itemMeta)
_CLASSREGISTER_AddVar(itemNum, Goods::itemNum)
_CLASSREGISTER_AddVar(coinId, Goods::coinId)
_CLASSREGISTER_AddVar(blockymodsPrice, Goods::blockymodsPrice)
_CLASSREGISTER_AddVar(blockmanPrice, Goods::blockmanPrice)
_CLASSREGISTER_AddVar(limit, Goods::limit)
_CLASSREGISTER_AddVar(desc, Goods::desc)
_CLASSREGISTER_AddVar(icon, Goods::icon)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RespawnGoods)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(time, RespawnGoods::time)
_CLASSREGISTER_AddVar(coinId, RespawnGoods::coinId)
_CLASSREGISTER_AddVar(blockymodsPrice, RespawnGoods::blockymodsPrice)
_CLASSREGISTER_AddVar(blockmanPrice, RespawnGoods::blockmanPrice)
_CLASSREGISTER_AddVar(times, RespawnGoods::times)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(Commodity)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, Commodity::itemId)
_CLASSREGISTER_AddVar(itemMeta, Commodity::itemMeta)
_CLASSREGISTER_AddVar(itemNum, Commodity::itemNum)
_CLASSREGISTER_AddVar(coinId, Commodity::coinId)
_CLASSREGISTER_AddVar(price, Commodity::price)
_CLASSREGISTER_AddVar(desc, Commodity::desc)
_CLASSREGISTER_AddVar(image, Commodity::image)
_CLASSREGISTER_AddVar(notify, Commodity::notify)
_CLASSREGISTER_AddVar(tipDesc, Commodity::tipDesc)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ItemStackInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ItemStackInfo::id)
_CLASSREGISTER_AddVar(meta, ItemStackInfo::meta)
_CLASSREGISTER_AddVar(num, ItemStackInfo::num)
_CLASSREGISTER_AddVar(bullets, ItemStackInfo::bullets)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorInfo::id)
_CLASSREGISTER_AddVar(manorId, ManorInfo::manorId)
_CLASSREGISTER_AddVar(rose, ManorInfo::rose)
_CLASSREGISTER_AddVar(level, ManorInfo::level)
_CLASSREGISTER_AddVar(price, ManorInfo::price)
_CLASSREGISTER_AddVar(value, ManorInfo::value)
_CLASSREGISTER_AddVar(houseId, ManorInfo::houseId)
_CLASSREGISTER_AddVar(charm, ManorInfo::charm)
_CLASSREGISTER_AddVar(maxLevel, ManorInfo::maxLevel)
_CLASSREGISTER_AddVar(seed, ManorInfo::seed)
_CLASSREGISTER_AddVar(ground, ManorInfo::ground)
_CLASSREGISTER_AddVar(icon, ManorInfo::icon)
_CLASSREGISTER_AddVar(currencyType, ManorInfo::currencyType)
_CLASSREGISTER_AddVar(isMaster, ManorInfo::isMaster)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorHouse)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorHouse::id)
_CLASSREGISTER_AddVar(price, ManorHouse::price)
_CLASSREGISTER_AddVar(charm, ManorHouse::charm)
_CLASSREGISTER_AddVar(unlockLevel, ManorHouse::unlockLevel)
_CLASSREGISTER_AddVar(cdTime, ManorHouse::cdTime)
_CLASSREGISTER_AddVar(icon, ManorHouse::icon)
_CLASSREGISTER_AddVar(name, ManorHouse::name)
_CLASSREGISTER_AddVar(isBuy, ManorHouse::isBuy)
_CLASSREGISTER_AddVar(currencyType, ManorHouse::currencyType)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorFurniture)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorFurniture::id)
_CLASSREGISTER_AddVar(price, ManorFurniture::price)
_CLASSREGISTER_AddVar(charm, ManorFurniture::charm)
_CLASSREGISTER_AddVar(icon, ManorFurniture::icon)
_CLASSREGISTER_AddVar(name, ManorFurniture::name)
_CLASSREGISTER_AddVar(operationType, ManorFurniture::operationType)
_CLASSREGISTER_AddVar(currencyType, ManorFurniture::currencyType)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ManorMessage)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, ManorMessage::id)
_CLASSREGISTER_AddVar(userId, ManorMessage::userId)
_CLASSREGISTER_AddVar(messageType, ManorMessage::messageType)
_CLASSREGISTER_AddVar(content, ManorMessage::content)
_CLASSREGISTER_AddVar(userName, ManorMessage::userName)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(ManorOwner)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(index, ManorOwner::index)
_CLASSREGISTER_AddVar(ownerId, ManorOwner::ownerId)
_CLASSREGISTER_AddVar(origin, ManorOwner::origin)
_CLASSREGISTER_AddVar(termini, ManorOwner::termini)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(GunPluginSetting)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(gunId, GunPluginSetting::gunId)
_CLASSREGISTER_AddVar(gunType, GunPluginSetting::gunType)
_CLASSREGISTER_AddVar(maxBulletNum, GunPluginSetting::maxBulletNum)
_CLASSREGISTER_AddVar(damage, GunPluginSetting::damage)
_CLASSREGISTER_AddVar(knockback, GunPluginSetting::knockback)
_CLASSREGISTER_AddVar(bulletId, GunPluginSetting::bulletId)
_CLASSREGISTER_AddVar(shootRange, GunPluginSetting::shootRange)
_CLASSREGISTER_AddVar(cdTime, GunPluginSetting::cdTime)
_CLASSREGISTER_AddVar(sniperDistance, GunPluginSetting::sniperDistance)
_CLASSREGISTER_AddVar(mouseSensitivity, GunPluginSetting::mouseSensitivity)
_CLASSREGISTER_AddVar(bulletPerShoot, GunPluginSetting::bulletPerShoot)
_CLASSREGISTER_AddVar(bulletOffset, GunPluginSetting::bulletOffset)
_CLASSREGISTER_AddVar(headshotDamage, GunPluginSetting::headshotDamage)
_CLASSREGISTER_AddVar(recoil, GunPluginSetting::recoil)
_CLASSREGISTER_AddVar(bulletEffect, GunPluginSetting::bulletEffect)
_CLASSREGISTER_AddVar(flameEffect, GunPluginSetting::flameEffect)
_CLASSREGISTER_AddVar(isPiercing, GunPluginSetting::isPiercing)
_CLASSREGISTER_AddVar(explosionRange, GunPluginSetting::explosionRange)
_CLASSREGISTER_AddVar(gravityVelocity, GunPluginSetting::gravityVelocity)
_CLASSREGISTER_AddVar(bounceTimes, GunPluginSetting::bounceTimes)
_CLASSREGISTER_AddVar(isAutoShoot, GunPluginSetting::isAutoShoot)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(MonsterSetting)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(monsterId, MonsterSetting::monsterId)
_CLASSREGISTER_AddVar(monsterBtTree, MonsterSetting::monsterBtTree)
_CLASSREGISTER_AddVar(monsterType, MonsterSetting::monsterType)
_CLASSREGISTER_AddVar(isAutoAttack, MonsterSetting::isAutoAttack)
_CLASSREGISTER_AddVar(attackDistance, MonsterSetting::attackDistance)
_CLASSREGISTER_AddVar(attackCd, MonsterSetting::attackCd)
_CLASSREGISTER_AddVar(attackCount, MonsterSetting::attackCount)
_CLASSREGISTER_AddVar(moveSpeed, MonsterSetting::moveSpeed)
_CLASSREGISTER_AddVar(attackType, MonsterSetting::attackType)
_CLASSREGISTER_AddVar(patrolDistance, MonsterSetting::patrolDistance)
_CLASSREGISTER_AddVar(skillId, MonsterSetting::skillId)
_CLASSREGISTER_AddVar(skillCd, MonsterSetting::skillCd)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(SkillEffect)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, SkillEffect::id)
_CLASSREGISTER_AddVar(name, SkillEffect::name)
_CLASSREGISTER_AddVar(duration, SkillEffect::duration)
_CLASSREGISTER_AddVar(width, SkillEffect::width)
_CLASSREGISTER_AddVar(height, SkillEffect::height)
_CLASSREGISTER_AddVar(density, SkillEffect::density)
_CLASSREGISTER_AddVar(color, SkillEffect::color)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(SkillItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(SkillId, SkillItem::SkillId)
_CLASSREGISTER_AddVar(Occupation, SkillItem::Occupation)
_CLASSREGISTER_AddVar(ItemId, SkillItem::ItemId)
_CLASSREGISTER_AddVar(ItemSkillCd, SkillItem::ItemSkillCd)
_CLASSREGISTER_AddVar(ItemSkillDistace, SkillItem::ItemSkillDistace)
_CLASSREGISTER_AddVar(MoveSpeed, SkillItem::MoveSpeed)
_CLASSREGISTER_AddVar(DropSpeed, SkillItem::DropSpeed)
_CLASSREGISTER_AddVar(AtlasName, SkillItem::AtlasName)
_CLASSREGISTER_AddVar(ItemIconName, SkillItem::ItemIconName)
_CLASSREGISTER_AddVar(AutoCast, SkillItem::AutoCast)
_CLASSREGISTER_AddVar(IsCrossHair, SkillItem::IsCrossHair)
_CLASSREGISTER_AddVar(Parabola, SkillItem::Parabola)
_CLASSREGISTER_AddVar(EffectName, SkillItem::EffectName)
_END_REGISTER_CLASS()

