// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_BASEAGENT_H_
#define _BEHAVIAC_BASEAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include "Entity/Entity.h"
///<<< END WRITING YOUR CODE

class BaseAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE BaseAgent
///<<< END WRITING YOUR CODE
{
public:
	BaseAgent();
	virtual ~BaseAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(BaseAgent, behaviac::Agent)

	private: void Attack();

	private: void BossFreeSkill();

	private: void FindTarget();

	private: behaviac::EBTStatus findTargetPlayer();

	private: void gotoHome();

	private: bool IsAlive();

	private: void Move();

	private: void MultipleAttack();

///<<< BEGIN WRITING YOUR CODE CLASS_PART
private:
	BLOCKMAN::Entity* m_entity = nullptr;
public:
	void setEntity(BLOCKMAN::Entity* entity) { m_entity = entity; };
	BLOCKMAN::Entity* getEntity() { return m_entity; }

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
