// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct METHOD_TYPE_BirdAgent_Attack { };
template<> inline behaviac::EBTStatus BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_Attack>()
{
	return this->BirdAgent::Attack();
}

struct METHOD_TYPE_BirdAgent_findFollowPos { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_findFollowPos>()
{
	this->BirdAgent::findFollowPos();
}

struct METHOD_TYPE_BirdAgent_findPatrolPos { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_findPatrolPos>()
{
	this->BirdAgent::findPatrolPos();
}

struct METHOD_TYPE_BirdAgent_FindTarget { };
template<> inline bool BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_FindTarget>()
{
	return this->BirdAgent::FindTarget();
}

struct METHOD_TYPE_BirdAgent_Gather { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_Gather>()
{
	this->BirdAgent::Gather();
}

struct METHOD_TYPE_BirdAgent_isLeaveMaster { };
template<> inline bool BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_isLeaveMaster>()
{
	return this->BirdAgent::isLeaveMaster();
}

struct METHOD_TYPE_BirdAgent_isMasterMoved { };
template<> inline bool BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_isMasterMoved>()
{
	return this->BirdAgent::isMasterMoved();
}

struct METHOD_TYPE_BirdAgent_isNeedGather { };
template<> inline bool BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_isNeedGather>()
{
	return this->BirdAgent::isNeedGather();
}

struct METHOD_TYPE_BirdAgent_jump { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_jump>()
{
	this->BirdAgent::jump();
}

struct METHOD_TYPE_BirdAgent_MakeCoin { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_MakeCoin>()
{
	this->BirdAgent::MakeCoin();
}

struct METHOD_TYPE_BirdAgent_Move { };
template<> inline behaviac::EBTStatus BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_Move>()
{
	return this->BirdAgent::Move();
}

struct METHOD_TYPE_BirdAgent_Patrol { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_Patrol>()
{
	this->BirdAgent::Patrol();
}

struct METHOD_TYPE_BirdAgent_selectPosNearPlayer { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_selectPosNearPlayer>()
{
	this->BirdAgent::selectPosNearPlayer();
}

struct METHOD_TYPE_BirdAgent_setBirdHomePosToTargetPos { };
template<> inline void BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_setBirdHomePosToTargetPos>()
{
	this->BirdAgent::setBirdHomePosToTargetPos();
}

struct METHOD_TYPE_BirdAgent_translateFruit { };
template<> inline behaviac::EBTStatus BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_translateFruit>()
{
	return this->BirdAgent::translateFruit();
}

struct METHOD_TYPE_BirdAgent_tryTeleportToMaster { };
template<> inline behaviac::EBTStatus BirdAgent::_Execute_Method_<METHOD_TYPE_BirdAgent_tryTeleportToMaster>()
{
	return this->BirdAgent::tryTeleportToMaster();
}


struct METHOD_TYPE_BaseAgent_Attack { };
template<> inline void BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_Attack>()
{
	this->BaseAgent::Attack();
}

struct METHOD_TYPE_BaseAgent_BossFreeSkill { };
template<> inline void BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_BossFreeSkill>()
{
	this->BaseAgent::BossFreeSkill();
}

struct METHOD_TYPE_BaseAgent_FindTarget { };
template<> inline void BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_FindTarget>()
{
	this->BaseAgent::FindTarget();
}

struct METHOD_TYPE_BaseAgent_findTargetPlayer { };
template<> inline behaviac::EBTStatus BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_findTargetPlayer>()
{
	return this->BaseAgent::findTargetPlayer();
}

struct METHOD_TYPE_BaseAgent_gotoHome { };
template<> inline void BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_gotoHome>()
{
	this->BaseAgent::gotoHome();
}

struct METHOD_TYPE_BaseAgent_IsAlive { };
template<> inline bool BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_IsAlive>()
{
	return this->BaseAgent::IsAlive();
}

struct METHOD_TYPE_BaseAgent_Move { };
template<> inline void BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_Move>()
{
	this->BaseAgent::Move();
}

struct METHOD_TYPE_BaseAgent_MultipleAttack { };
template<> inline void BaseAgent::_Execute_Method_<METHOD_TYPE_BaseAgent_MultipleAttack>()
{
	this->BaseAgent::MultipleAttack();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
