// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline behaviac::EBTStatus FunctionPointer_BirdAgent_Attack(Agent* self) { return (behaviac::EBTStatus)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_Attack, behaviac::EBTStatus >(); }
	inline void FunctionPointer_BirdAgent_Attack_Task(Agent* self) { } /* Attack_Task */
	inline void FunctionPointer_BirdAgent_findFollowPos(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_findFollowPos, void >(); }
	inline void FunctionPointer_BirdAgent_findPatrolPos(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_findPatrolPos, void >(); }
	inline bool FunctionPointer_BirdAgent_FindTarget(Agent* self) { return (bool)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_FindTarget, bool >(); }
	inline void FunctionPointer_BirdAgent_Gather(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_Gather, void >(); }
	inline bool FunctionPointer_BirdAgent_isInFruitField(Agent* self) { return ((BirdAgent*)self)->isInFruitField(); }
	inline bool FunctionPointer_BirdAgent_isLeaveMaster(Agent* self) { return (bool)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_isLeaveMaster, bool >(); }
	inline bool FunctionPointer_BirdAgent_isMasterMoved(Agent* self) { return (bool)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_isMasterMoved, bool >(); }
	inline bool FunctionPointer_BirdAgent_isNeedGather(Agent* self) { return (bool)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_isNeedGather, bool >(); }
	inline void FunctionPointer_BirdAgent_jump(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_jump, void >(); }
	inline void FunctionPointer_BirdAgent_LogMessage(char* param0) { BirdAgent::LogMessage(param0); }
	inline void FunctionPointer_BirdAgent_MakeCoin(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_MakeCoin, void >(); }
	inline behaviac::EBTStatus FunctionPointer_BirdAgent_Move(Agent* self) { return (behaviac::EBTStatus)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_Move, behaviac::EBTStatus >(); }
	inline void FunctionPointer_BirdAgent_Patrol(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_Patrol, void >(); }
	inline void FunctionPointer_BirdAgent_selectPosNearPlayer(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_selectPosNearPlayer, void >(); }
	inline void FunctionPointer_BirdAgent_setBirdHomePosToTargetPos(Agent* self) { ((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_setBirdHomePosToTargetPos, void >(); }
	inline void FunctionPointer_BirdAgent_translate_task(Agent* self) { } /* translate_task */
	inline behaviac::EBTStatus FunctionPointer_BirdAgent_translateFruit(Agent* self) { return (behaviac::EBTStatus)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_translateFruit, behaviac::EBTStatus >(); }
	inline behaviac::EBTStatus FunctionPointer_BirdAgent_tryTeleportToMaster(Agent* self) { return (behaviac::EBTStatus)((BirdAgent*)self)->_Execute_Method_<METHOD_TYPE_BirdAgent_tryTeleportToMaster, behaviac::EBTStatus >(); }
	inline void FunctionPointer_BaseAgent_Attack(Agent* self) { ((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_Attack, void >(); }
	inline void FunctionPointer_BaseAgent_BossFreeSkill(Agent* self) { ((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_BossFreeSkill, void >(); }
	inline void FunctionPointer_BaseAgent_FindTarget(Agent* self) { ((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_FindTarget, void >(); }
	inline behaviac::EBTStatus FunctionPointer_BaseAgent_findTargetPlayer(Agent* self) { return (behaviac::EBTStatus)((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_findTargetPlayer, behaviac::EBTStatus >(); }
	inline void FunctionPointer_BaseAgent_gotoHome(Agent* self) { ((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_gotoHome, void >(); }
	inline bool FunctionPointer_BaseAgent_IsAlive(Agent* self) { return (bool)((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_IsAlive, bool >(); }
	inline void FunctionPointer_BaseAgent_LogMessage(char* param0) { BaseAgent::LogMessage(param0); }
	inline void FunctionPointer_BaseAgent_Move(Agent* self) { ((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_Move, void >(); }
	inline void FunctionPointer_BaseAgent_MultipleAttack(Agent* self) { ((BaseAgent*)self)->_Execute_Method_<METHOD_TYPE_BaseAgent_MultipleAttack, void >(); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
