// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_BIRDAGENT_H_
#define _BEHAVIAC_BIRDAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include "Entity/Entity.h"
///<<< END WRITING YOUR CODE

class BirdAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE BirdAgent
///<<< END WRITING YOUR CODE
{
public:
	BirdAgent();
	virtual ~BirdAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(BirdAgent, behaviac::Agent)

	private: behaviac::EBTStatus Attack();

	private: void findFollowPos();

	private: void findPatrolPos();

	private: bool FindTarget();

	private: void Gather();

	public: bool isInFruitField();

	private: bool isLeaveMaster();

	private: bool isMasterMoved();

	private: bool isNeedGather();

	private: void jump();

	private: void MakeCoin();

	private: behaviac::EBTStatus Move();

	private: void Patrol();

	private: void selectPosNearPlayer();

	private: void setBirdHomePosToTargetPos();

	private: behaviac::EBTStatus translateFruit();

	private: behaviac::EBTStatus tryTeleportToMaster();

///<<< BEGIN WRITING YOUR CODE CLASS_PART
private:
	BLOCKMAN::Entity* m_entity = nullptr;
	ui64 m_lastCheckHasLeaveMaster = 0;
public:
	void setEntity(BLOCKMAN::Entity* entity) { m_entity = entity; };
	BLOCKMAN::Entity* getEntity() { return m_entity; }
///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
