// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "BirdAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include "World/World.h"
#include "Entity/EntityBird.h"
#include "Blockman/Entity/EntityBirdAI.h"
#include "Server.h"
///<<< END WRITING YOUR CODE

BirdAgent::BirdAgent()
{
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

BirdAgent::~BirdAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus BirdAgent::Attack()
{
///<<< BEGIN WRITING YOUR CODE Attack
	return behaviac::BT_SUCCESS;
	///<<< END WRITING YOUR CODE
}

void BirdAgent::findFollowPos()
{
///<<< BEGIN WRITING YOUR CODE findFollowPos
	//if (m_lastCheckHasLeaveMaster != 0 && Root::Instance()->getCurrentTime() - m_lastCheckHasLeaveMaster < 1000)
	//	return false;
	//m_lastCheckHasLeaveMaster = Root::Instance()->getCurrentTime();


///<<< END WRITING YOUR CODE
}

void BirdAgent::findPatrolPos()
{
///<<< BEGIN WRITING YOUR CODE findPatrolPos

///<<< END WRITING YOUR CODE
}

bool BirdAgent::FindTarget()
{
///<<< BEGIN WRITING YOUR CODE FindTarget
	return false;
///<<< END WRITING YOUR CODE
}

void BirdAgent::Gather()
{
///<<< BEGIN WRITING YOUR CODE Gather
///<<< END WRITING YOUR CODE
}

bool BirdAgent::isInFruitField()
{
///<<< BEGIN WRITING YOUR CODE isInFruitField
	return false;
///<<< END WRITING YOUR CODE
}

bool BirdAgent::isLeaveMaster()
{
///<<< BEGIN WRITING YOUR CODE isLeaveMaster
	EntityBirdAI* pBird = dynamic_cast<EntityBirdAI*>(getEntity());
	if (!pBird)
		return true;
	else
		return pBird->hasLeaveMaster();

///<<< END WRITING YOUR CODE
}

bool BirdAgent::isMasterMoved()
{
///<<< BEGIN WRITING YOUR CODE isMasterMoved
	return false;
///<<< END WRITING YOUR CODE
}

bool BirdAgent::isNeedGather()
{
///<<< BEGIN WRITING YOUR CODE isNeedGather
	return false;
///<<< END WRITING YOUR CODE
}

void BirdAgent::jump()
{
///<<< BEGIN WRITING YOUR CODE jump
///<<< END WRITING YOUR CODE
}

void BirdAgent::MakeCoin()
{
///<<< BEGIN WRITING YOUR CODE MakeCoin
///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus BirdAgent::Move()
{
///<<< BEGIN WRITING YOUR CODE Move
	EntityBirdAI* pBird = dynamic_cast<EntityBirdAI*>(getEntity());
	if (!pBird)
		return behaviac::EBTStatus::BT_SUCCESS;

	if (pBird->getPathEntity() == nullptr)
		return behaviac::EBTStatus::BT_SUCCESS;
	else
		return behaviac::BT_RUNNING;
///<<< END WRITING YOUR CODE
}

void BirdAgent::Patrol()
{
///<<< BEGIN WRITING YOUR CODE Patrol
///<<< END WRITING YOUR CODE
}

void BirdAgent::selectPosNearPlayer()
{
///<<< BEGIN WRITING YOUR CODE selectPosNearPlayer
///<<< END WRITING YOUR CODE
}

void BirdAgent::setBirdHomePosToTargetPos()
{
///<<< BEGIN WRITING YOUR CODE setBirdHomePosToTargetPos
///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus BirdAgent::translateFruit()
{
///<<< BEGIN WRITING YOUR CODE translateFruit
	return behaviac::BT_RUNNING;
///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus BirdAgent::tryTeleportToMaster()
{
///<<< BEGIN WRITING YOUR CODE tryTeleportToMaster

	return behaviac::EBTStatus::BT_SUCCESS;


///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
