/********************************************************************
filename: 	DataPacket
file path:	H:\sandboxol\client\blockmango-client\dev\common\Src\network\packet\DataPacket.h

version:	1
author:		qutianxiang
company:    sandboxol
date:		2017/06/19
*********************************************************************/


//-----------------------------------------
//| id | data |
//----------------------------------------


#ifndef __DATAPACKET_HEADER__
#define __DATAPACKET_HEADER__

#include "NetDataStream.h"
#include "Serializer.h"

enum class S2CPacketType
{
	ProtocolBegin = 0,
	GameInfo = 1,
	Disconnect = 2,
	AddPlayer = 3,
	UpdateBlocks = 4,
	PlayerList = 5,
	MovePlayer = 6,
	EntityMovement = 7,
	EntityTeleport = 8,
	EntityVelocity = 9,
	EntityHeadRotation = 10,
	SpawnVehicle = 11,
	SpawnPlayer = 12,
	SpawnExpOrb = 13,
	SpawnMob = 14,
	RemoveEntity = 15,
	Animate = 16,
	UpdatePlayerAttribute = 17,
	Rebirth = 18,
	PlayerAction = 19,
	CraftItem = 20,
	EquipArmors = 21,
	UnequipArmor = 22,
	DestroyArmor = 23,
	ChangeItemInHand = 24,
	ChangeCurrentItem = 25,
	PlayerInventory = 26,
	ChatMessageString = 27,
	ChatMessageTranslation = 28,
	PlayerInvisible = 29,
	AddEntityEffect = 30,
	RemoveEntityEffect = 31,
	ChestInventory = 32,
	UsePropResults = 33,
	UserIn = 34,
	UserOut = 35,
	LoginFailure = 36,
	Ping = 37,
	SyncWorldTime = 38,
	ChatMessageNotification = 39,
	Settlement = 40,
	Gameover = 41,
	CloseContainer = 42,
	PlaySound = 43,
	Explosion = 44,
	SetSignTexts = 45,
	SetAllowFlying = 46,
	ChangePlayerInfo = 47,
	GameStatus = 48,
	SetWatchMode = 49,
	UpdateMerchant = 50,
	SetFlying = 51,
	PlayerSettlement = 52,
	GameSettlement = 53,
	UserAttr = 54,
	DebugString = 55,
	PlayerLifeStatus = 56,
	SyncWorldWeather = 57,
	BedDestroy = 58,
	CheckCSVersionResult = 59,
	RespawnCountdown = 60,
	AllPlayerTeamInfo = 61,
	ChangePlayerTeam = 62,
	PlayerChangeActor = 63,
	PlayerRestoreActor = 64,
	ReloadBullet = 65,
	UpdateShop = 66,
	UpdateShopGoods = 67,
	ShoppingResult = 68,
	InitMoney = 69,
	SyncGunFireResult = 70,
	SyncTakeVehicle = 71,
	ChangeMaxHealth = 72,
	UpdateCurrency = 73,
	SelectRoleData = 74,
	SyncPlayerOwnVehicle = 75,
	SyncLockVehicle = 76,
	SyncVehicleState = 77,
	SyncVehicleAction = 78,
	NotifyGetMoney = 79,
	NotifyGetItem = 80,
	BuyCommodityResult = 81,
	ShowBuyRespawn = 82,
	BuyRespawnResult = 83,
	ShowGoNpcMerchant = 84,
	UpdateBackpack = 85,
	RankData = 86,
	ActivateTrigger = 87,
	UpdateRankNpc = 88,
	TakeAircraft = 89,
	AircraftStartFly = 90,
	SyncAircraftState = 91,
	FriendOperation = 92,
	ChangeAircraftUI = 93,
	AirDorp = 94,
	PoisonCircleRange = 95,
	MemberLeftAndKill = 96,
	SyncBlockDestroyeFailure = 97,
	SkillType = 98,
	SyncChangePlayerActorInfo = 99,
	SyncNpcActorInfo = 100,
	SyncHideAndSeekBtnStatus = 101,
	EntitySkillEffect = 102,
	PickUpItemOrder = 103,
	RequestResult = 104,
	SyncGameTimeShowUi = 105,
	SyncCreateArrowTipMark = 106,
	SyncCameraLock = 107,
	DeathUnequipArmor = 108,
	SyncChangeEntityPerspece = 109,
	ChangeHeart = 110,
	UpdateRealTimeRankInfo = 111,
	UpdateGameMonsterInfo = 112,
	UpdateBossBloodStrip = 113,
	SwitchablePropsData = 114,
	UpgradePropsData = 115,
	PersonalShopTip = 116,
	CreateHouseFromSchematic = 117,
	SyncEntityCreature = 118,
	SyncCreatureEntityAction = 119,
	PlayerSpeedLevel = 120,
	PlayerExpInfo = 121,
	FillAreaByBlockIdAndMate = 122,
	ShowPlayerOperation = 123,
	ManorBtnVisible = 124,
	CallOnManorResetClient = 125,
	UpdateManorOwner = 126,
	SpawnCreatureBullet = 127,
	ShowUpgradeResourceUI = 128,
	UpdateBasementLife = 129,
	CustomTipMsg = 130,
	EntityPlayerOccupation = 131,
	SpwanSkillItemThrowable = 132,
	SyncSessionNpc = 133,
	UpdateManor = 134,
	SyncPlayerMovementInput = 135,
	SyncPlayerRotation = 136,
	SyncPlayerJumpChanged = 137,
	EntityPlayerTeleport = 138,
	SyncPlayerDownChanged = 139,
	SyncPlayerSetFlyingState = 140,
	GameTipNotification = 141,
	UpdateChestInventory = 142,
	UpdateMerchantInfo = 143,
	UpdateMerchantCommodities = 144,
	SyncShowMaskTime = 145,
	ShowBuildWarBlockBtn = 146,
	ShowBuildWarPlayNum = 147,
	ShowBuildWarLeftNum = 148,
	OpenShopByEntityId = 149,
	ShowBuildWarGrade = 150,
	ShowBuildWarGuessResult = 151,
	ShowBuildWarGuessUi = 152,
	GameSettlementExtra = 153,
	UnlockedCommodity = 154,
	InitUnlockedCommodity = 155,
	CloseBGM = 156,
	SetArmItem = 157,
	TeamResourcesUpdate = 158,
	ActorNpcContent = 159,
	BuildProgress = 160,
	EnchantmentPropsData = 161,
	PersonalSuperPropsData = 162,
	EnableMovement = 163,
	ConsumeCoinTip = 164,
	SuperPropsData = 165,
	SuperShopTip = 166,
	ChangeDefense = 167,
	ChangeAttack = 168,
	AddSimpleEffect = 169,
	EnterOtherGame = 170,
	KillMsg = 171,
	ShowPersonalShop = 172,
	PersonalShopArea = 173,
	AddGunBulletNum = 174,
	SubGunRecoil = 175,
	CustomPropsData = 176,
	UpdateCustomProps = 177,
	SyncEntityBlockman = 178,
	BlockmanMoveAttr = 179,
	CarDirection = 180,
	CarProgress = 181,
	EntityFrozenTime = 182,
	EntityPlayerTeleportWithMotion = 183,
	SyncCannonActorInfo = 184,
	SpawnCannon = 185,
	SyncCannonFire = 186,
	SubGunFireCd = 187,
	CropInfo = 188,
	SyncRanchInfo = 189,
	SyncRanchHouse = 190,
	SyncRanchStorage = 191,
	SyncRanchRank = 192,
	SyncRanchBuild = 193,
	SyncEntityBuildNpc = 194,
	SyncEntityLandNpc = 195,
	RanchGain = 196,
	SyncRanchOrder = 197,
	SyncRanchAchievement = 198,
	SyncPlayerSpecialJump = 199,
	ShowRanchExTip = 200,
	ShowRanchExTask = 201,
	BroadcastMessage = 202,
	GotoOtherGame = 203,
	RanchUnlockItem = 204,
	ShowRanchExCurrentItemInfo = 205,
	ShowRanchExItem = 206,
	RanchTimePrice = 207,
	RanchShortcutFreeTimes = 208,
	AppExpResult = 209,
	OccupationUnlock = 210,
	BuyFlying = 211,
	PlayCloseup = 212,
	ShowBuyKeepItemTip = 213,
	SendOpenEnchantment = 214,
	EntityHurtTime = 215,
	LotteryData = 216,
	LotteryResult = 217,
	HideAndSeekHallResult = 218,
	EntityColorfulTime = 219,
	EntitySelected = 220,
	SyncPlayerSetSpYaw = 221,
	EntityDisableMoveTime = 222,
	SendOpenPixelGunHallModeSelect = 223,
	UpdateStoreGunData = 224,
	UpdateStorePropData = 225,
	SyncEffectGunFire = 226,
	SyncEffectGunFireAtEntityResult = 227,
	SyncEffectGunFireAtBlockResult = 228,
	SyncEffectGunFireExplosionResult = 229,
	StopLaserGun = 230,
	ShowGunStore = 231,
	ShowPixelGunHallInfo = 232,
	ShowChestLottery = 233,
	SendOpenPixelGun1v1 = 234,
	SendOpenPixelGunRevive = 235,
	ChestLotteryResult = 236,
	UpdateLotteryChestData = 237,
	ShowPixelGunGamePerson = 238,
	ShowPixelGunGame1v1 = 239,
	ShowPixelGunGameTeam = 240,
	LogicSettingInfo = 241,
	SendOpenArmorUpgrade = 242,
	SendOpenPixelGunResult = 243,
	PlayerCurrentSeasonInfo = 244,
	PlayerLastSeasonInfo = 245,
	EnableAutoShoot = 246,
	Disarmament = 247,
	SetPlayerOpacity = 248,
	SendOpenPixelGunLvUp = 249,
	SendOpenPixelGunResultSpecialInfo = 250,
	NotifyGetGoods = 251,
	ShowSeasonRank = 252,
	PlayerNamePerspective = 253,
	AddCustomEffect = 254,
	SyncCustomEffect = 255,
	SyncEntityBulletin = 256,
	SyncEntityBird = 257,
	SyncPlayerBagInfo = 258,
	SyncBirdStore = 259,
	SyncBirdPersonalStore = 260,
	SyncBirdBag = 261,
	SyncBirdPlayerInfo = 262,
	SyncBirdDress = 263,
	SyncBirdFood = 264,
	SyncBirdTask = 265,
	SyncBirdAtlas = 266,
	BirdGain = 267,
	BirdNestOperation = 268,
	SyncBirdScope = 269,
	SyncBirdActivity = 270,
	BirdLotteryResult = 271,
	SyncEntityAction = 272,
	SyncBirdTimePrice = 273,
	BirdAddScore = 274,
	SyncBirdBuff = 275,
	SyncEntityHealth = 276,
	SyncBirdSimulatorStoreItem = 277,
	SyncBirdSimulatorTaskItem = 278,
	SyncBirdSimulatorPersonStoreTab = 279,
	ChangeGuideArrowStatus = 280,
	AddWallText = 281,
	DeleteWallText = 282,
	ProtocolEnd
};

constexpr  S2CPacketType operator -(S2CPacketType type, int  i)
{
	return static_cast<S2CPacketType>(static_cast<int>(type) - i);
}

constexpr  S2CPacketType operator +(S2CPacketType type, int  i)
{
	return static_cast<S2CPacketType>(static_cast<int>(type) + i);
}


enum class C2SPacketType
{
	ProtocolBegin = 0,
	CheckCSVersion = 1,
	Login = 2,
	Logout = 3,
	ClientReady = 4,
	Attack = 5,
	Animate = 6,
	PlayerMovement = 7,
	VehicleMovement = 8,
	Rebirth = 9,
	PlayerAction = 10,
	CraftWithCraftingTable = 11,
	CraftWithHand = 12,
	SwapItemPosition = 13,
	DropItemPosition = 14,
	EquipArmor = 15,
	UnequipArmor = 16,
	ChangeItemInHand = 17,
	ChangeCurrentItem = 18,
	UseItem = 19,
	StartBreakBlock = 20,
	AbortBreakBlock = 21,
	FinishBreakBlock = 22,
	PlaceBlock = 23,
	ChatMessageString = 24,
	ChatMessageTranslation = 25,
	ActivateBlock = 26,
	ExchangeItemStack = 27,
	UseProp = 28,
	Ping = 29,
	LaunchArrow = 30,
	LaunchBullet = 31,
	SpawnVehicle = 32,
	GunFireResult = 33,
	CloseContainer = 34,
	UseThrowableItem = 35,
	SplashPotion = 36,
	SetFlying = 37,
	BuyCommodity = 38,
	TakeVehicle = 39,
	GunShootTarget = 40,
	ReloadBullet = 41,
	BuyGoods = 42,
	ResumeOrder = 43,
	SelectRole = 44,
	BuyVehicle = 45,
	LockVehicle = 46,
	VehicleAction = 47,
	BuyRespawn = 48,
	GoNpcMerchant = 49,
	ClickTeleport = 50,
	LeaveAircraft = 51,
	ChangeClothes = 52,
	RestClothes = 53,
	FriendOperation = 54,
	SetParachute = 55,
	SkillType = 56,
	ChangePlayerActor = 57,
	ClickChangeActor = 58,
	CameraLockMovement = 59,
	CameraLock = 60,
	PickUpItemPay = 61,
	AttackActorNpc = 62,
	GetManor = 63,
	SellManor = 64,
	UpgradeManor = 65,
	BuyHouse = 66,
	BuyFurniture = 67,
	DeleteManorMessage = 68,
	BuildHouse = 69,
	PutFurniture = 70,
	RecycleFurniture = 71,
	ManorTeleport = 72,
	CallOnManor = 73,
	GiveRose = 74,
	RequestUpdateRealTimeRank = 75,
	BuySwitchableProp = 76,
	BuyUpgradeProp = 77,
	AttackCreatureEntity = 78,
	UpgradeResource = 79,
	WatchRespawn = 80,
	MovementInput = 81,
	SendJumpChanged = 82,
	SendPlayerRotation = 83,
	SendDownChanged = 84,
	NeedUpdateMerchantCommodities = 85,
	SyncCustomTipResult = 86,
	RelaseItemSkill = 87,
	BuildWarOpenShop = 88,
	BuildWarGrade = 89,
	BuildWarOpenGuessResult = 90,
	BuildWarGuessVisit = 91,
	BuildWarGuessSuc = 92,
	BuildWarShowResult = 93,
	GetCommodity = 94,
	UnlockCommodity = 95,
	BreakBlockInstantly = 96,
	PlayerInteractionActionMesage = 97,
	AttackEntity = 98,
	BuyEnchantmentProp = 99,
	ConsumeTipResult = 100,
	BuySuperProp = 101,
	BuyCustomProp = 102,
	ClickBackHall = 103,
	LongHitEntity = 104,
	UseFishingRod = 105,
	UseCannon = 106,
	UpdateUserMoney = 107,
	BuyBullet = 108,
	RanchBuyItem = 109,
	RanchBuyBuildItem = 110,
	RanchOperation = 111,
	RanchReceive = 112,
	RanchExpand = 113,
	RanchShortcut = 114,
	RanchDestroyHouse = 115,
	RanchSellItem = 116,
	RanchBuyItems = 117,
	RanchBuildTakeProduct = 118,
	RanchBuildQueueOperation = 119,
	RanchBuildRemove = 120,
	RanchOrderOperate = 121,
	RanchExBegin = 122,
	RanchExTaskFinish = 123,
	RanchGiftsOrInvite = 124,
	RanchHelpFinish = 125,
	ReceiveMailReward = 126,
	ReceiveRanchAchievementReward = 127,
	RanchGoExplore = 128,
	ChangeCurrentItemInfo = 129,
	SpeedUpCrop = 131,
	UseCubeFinshOrder = 132,
	BuyFlyingPermissionResult = 133,
	ResetCloseup = 134,
	KeepItem = 135,
	OpenEnchantMent = 136,
	EnchantmentEffectClick = 137,
	EnchantmentQuick = 138,
	SelectLottery = 139,
	LotteryAgain = 140,
	HallLotteryAgain = 141,
	SetSpYaw = 142,
	OpenSelectMode = 143,
	UseStoreGun = 144,
	BuyStoreGun = 145,
	UpgradeStoreGun = 146,
	QuickUpgradeStoreGun = 147,
	UseStoreProp = 148,
	BuyStoreProp = 149,
	UpgradeStoreProp = 150,
	QuickUpgradeStoreProp = 151,
	UnloadStoreProp = 152,
	EffectGunFire = 153,
	EffectGunFireResult = 154,
	EffectGunFireExplosionResult = 155,
	StopLaserGun = 156,
	PixelGunHallUnlockMap = 157,
	FirstShowStoreGun = 158,
	FirstShowStoreProp = 159,
	PixelGunSelectBox = 160,
	PixelGunExit = 161,
	PixelGunRematch = 162,
	PixelGunRevive = 163,
	OpenLotteryChest = 164,
	OpenArmorUpgrade = 165,
	UpgradeArmor = 166,
	PixelGunResultBack = 167,
	PixelGunResultNext = 168,
	PixelGunResultRevenge = 169,
	PixelGunFight = 170,
	ConsumeBullet = 171,
	BirdBagOperation = 172,
	BirdStoreOperation = 173,
	BirdPersonalStoreBuyGoods = 174,
	BirdFuse = 175,
	BirdOpenTreasureChest = 176,
	BirdLottery = 177,
	BirdTask = 178,
	BirdFeed = 179,
	BirdSetDress = 180,
	ProtocolEnd
};

constexpr  C2SPacketType operator -(C2SPacketType type, int  i)
{
	return static_cast<C2SPacketType>(static_cast<int>(type) - i);
}

constexpr  C2SPacketType operator +(C2SPacketType type, int  i)
{
	return static_cast<C2SPacketType>(static_cast<int>(type) + i);
}

class DataPacket: public NetDataStream, public LORD::ObjectAlloc
{

public:
	enum PacketChannel
	{
		emNormal = 1,
		emUserAction,
		emMapData
	};

public:
	DataPacket(void){};
	virtual ~DataPacket(void){};

	virtual ui16  pid(){return 0;};
	virtual int  channel(){return 0;} 

	virtual void encode(){};
	virtual void decode(){};

	void    setSender(ui64 ssid){this->m_sender = ssid;}
	ui64    getSender(){return m_sender;}
private:

	ui64  m_sender = 0;
};

#endif
