#include "Network/ClientPeer.h"
#include "Network/HttpRequest.h"
#include "LuaRegister/Template/LuaRegister.h"

_BEGIN_REGISTER_CLASS(ClientPeer)
_CLASSREGISTER_AddMember(getEntityRuntimeID, ClientPeer::getEntityRuntimeID)
_CLASSREGISTER_AddMember(getRakssid, ClientPeer::getRakssid)
_CLASSREGISTER_AddMember(getPlatformUserId, ClientPeer::getPlatformUserId)
_CLASSREGISTER_AddMember(getEntityPlayer, ClientPeer::getEntityPlayer)
_CLASSREGISTER_AddMember(getName, ClientPeer::getName)
_CLASSREGISTER_AddMember(sendLoginResult, ClientPeer::sendLoginResult)
_CLASSREGISTER_AddMember(setShowName, ClientPeer::setShowName)
_CLASSREGISTER_AddMember(buyChangeActor, ClientPeer::buyChangeActor)
_CLASSREGISTER_AddMember(pickupItemPay, ClientPeer::pickupItemPay)
_CLASSREGISTER_AddMember(consumeDiamonds, ClientPeer::consumeDiamonds)
_CLASSREGISTER_AddMember(isVisitor, ClientPeer::isVisitor)
_CLASSREGISTER_AddMember(setRespawnPos, ClientPeer::setRespawnPos)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(HttpRequest)
_CLASSREGISTER_AddStaticMember(syncGet, HttpRequest::syncGet)
_CLASSREGISTER_AddStaticMember(syncPost, HttpRequest::syncPost)
_CLASSREGISTER_AddStaticMember(asyncGet, HttpRequest::asyncGet)
_CLASSREGISTER_AddStaticMember(asyncPost, HttpRequest::asyncPost)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RoomGameConfig)
_CLASSREGISTER_AddVar(gameId, RoomGameConfig::gameId)
_CLASSREGISTER_AddVar(gameName, RoomGameConfig::gameName)
_CLASSREGISTER_AddVar(gameIp, RoomGameConfig::gameIp)
_CLASSREGISTER_AddVar(serverPort, RoomGameConfig::serverPort)
_CLASSREGISTER_AddVar(monitorAddr, RoomGameConfig::monitorAddr)
_CLASSREGISTER_AddVar(gameType, RoomGameConfig::gameType)
_CLASSREGISTER_AddVar(maxPlayers, RoomGameConfig::maxPlayers)
_CLASSREGISTER_AddVar(userConfig, RoomGameConfig::userConfig)
_CLASSREGISTER_AddVar(propAddr, RoomGameConfig::propAddr)
_CLASSREGISTER_AddVar(rankAddr, RoomGameConfig::rankAddr)
_CLASSREGISTER_AddVar(rewardAddr, RoomGameConfig::rewardAddr)
_CLASSREGISTER_AddVar(isChina, RoomGameConfig::isChina)
_CLASSREGISTER_AddVar(blockymodsRewardAddr, RoomGameConfig::blockymodsRewardAddr)
_END_REGISTER_CLASS()
