#include "LuaRegister/Template/LuaRegister.h"
#include "World/Ranch.h"
#include "World/BirdSimulator.h"
#include "Setting/RanchSetting.h"
#include "Entity/EntityBuildNpc.h"

using namespace BLOCKMAN;
using namespace LUA_REGISTER;

// Register Class Ranch
_BEGIN_REGISTER_CLASS(Ranch)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(setInfo, Ranch::setInfo)
_CLASSREGISTER_AddMember(setHouse, Ranch::setHouse)
_CLASSREGISTER_AddMember(setStorage, Ranch::setStorage)
_CLASSREGISTER_AddMember(updateStorageById, Ranch::updateStorageById)
_CLASSREGISTER_AddMember(setRankByType, Ranch::setRankByTypeFromLua)
_CLASSREGISTER_AddMember(setBuildByType, Ranch::setBuildByTypeFromLua)
_CLASSREGISTER_AddMember(setOrders, Ranch::setOrdersFromLua)
_CLASSREGISTER_AddMember(setAchievements, Ranch::setAchievementsFromLua)
_CLASSREGISTER_AddMember(setTimePrices, Ranch::setTimePricesFromLua)
_CLASSREGISTER_AddMember(setShortcutFreeTimes, Ranch::setShortcutFreeTimesFromLua)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(RanchCommon)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, RanchCommon::itemId)
_CLASSREGISTER_AddVar(num, RanchCommon::num)
_CLASSREGISTER_AddVar(price, RanchCommon::price)
_CLASSREGISTER_AddVar(userId, RanchCommon::userId)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(index, RanchInfo::index)
_CLASSREGISTER_AddVar(level, RanchInfo::level)
_CLASSREGISTER_AddVar(exp, RanchInfo::exp)
_CLASSREGISTER_AddVar(giftNum, RanchInfo::giftNum)
_CLASSREGISTER_AddVar(sendGiftCount, RanchInfo::sendGiftCount)
_CLASSREGISTER_AddVar(achievementPoint, RanchInfo::achievementPoint)
_CLASSREGISTER_AddVar(nextExp, RanchInfo::nextExp)
_CLASSREGISTER_AddVar(prosperity, RanchInfo::prosperity)
_CLASSREGISTER_AddVar(taskStartLevel, RanchInfo::taskStartLevel)
_CLASSREGISTER_AddVar(exploreStartLevel, RanchInfo::exploreStartLevel)
_CLASSREGISTER_AddVar(prosperityRank, RanchInfo::prosperityRank)
_CLASSREGISTER_AddVar(achievementRank, RanchInfo::achievementRank)
_CLASSREGISTER_AddVar(clanRank, RanchInfo::clanRank)
_CLASSREGISTER_AddVar(isCanFlying, RanchInfo::isCanFlying)
_CLASSREGISTER_AddVar(isDestroyHouse, RanchInfo::isDestroyHouse)
_CLASSREGISTER_AddVar(isDestroyWarehouse, RanchInfo::isDestroyWarehouse)
_CLASSREGISTER_AddVar(startPos, RanchInfo::startPos)
_CLASSREGISTER_AddVar(endPos, RanchInfo::endPos)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchStorage)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(level, RanchStorage::level)
_CLASSREGISTER_AddVar(maxLevel, RanchStorage::maxLevel)
_CLASSREGISTER_AddVar(capacity, RanchStorage::capacity)
_CLASSREGISTER_AddVar(nextCapacity, RanchStorage::nextCapacity)
_CLASSREGISTER_AddVar(upgradePrice, RanchStorage::upgradePrice)
_CLASSREGISTER_AddVar(needPlayerLevel, RanchStorage::needPlayerLevel)
_CLASSREGISTER_AddVar(items, RanchStorage::items)
_CLASSREGISTER_AddVar(upgradeRecipe, RanchStorage::upgradeRecipe)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchHouse)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchHouse::id)
_CLASSREGISTER_AddVar(level, RanchHouse::level)
_CLASSREGISTER_AddVar(maxLevel, RanchHouse::maxLevel)
_CLASSREGISTER_AddVar(nextLevel, RanchHouse::nextLevel)
_CLASSREGISTER_AddVar(upgradePrice, RanchHouse::upgradePrice)
_CLASSREGISTER_AddVar(needPlayerLevel, RanchHouse::needPlayerLevel)
_CLASSREGISTER_AddVar(icon, RanchHouse::icon)
_CLASSREGISTER_AddVar(name, RanchHouse::name)
_CLASSREGISTER_AddVar(nextIcon, RanchHouse::nextIcon)
_CLASSREGISTER_AddVar(nextName, RanchHouse::nextName)
_CLASSREGISTER_AddVar(upgradeRecipe, RanchHouse::upgradeRecipe)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchRank)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchRank::id)
_CLASSREGISTER_AddVar(level, RanchRank::level)
_CLASSREGISTER_AddVar(rank, RanchRank::rank)
_CLASSREGISTER_AddVar(value, RanchRank::value)
_CLASSREGISTER_AddVar(name, RanchRank::name)
_CLASSREGISTER_AddVar(userNum, RanchRank::userNum)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchBuild)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchBuild::id)
_CLASSREGISTER_AddVar(price, RanchBuild::price)
_CLASSREGISTER_AddVar(num, RanchBuild::num)
_CLASSREGISTER_AddVar(maxNum, RanchBuild::maxNum)
_CLASSREGISTER_AddVar(needLevel, RanchBuild::needLevel)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ProductQueue)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(queueId, ProductQueue::queueId)
_CLASSREGISTER_AddVar(productId, ProductQueue::productId)
_CLASSREGISTER_AddVar(outputNum, ProductQueue::outputNum)
_CLASSREGISTER_AddVar(timeLeft, ProductQueue::timeLeft)
_CLASSREGISTER_AddVar(needTime, ProductQueue::needTime)
_CLASSREGISTER_AddVar(unlockPrice, ProductQueue::unlockPrice)
_CLASSREGISTER_AddVar(currencyType, ProductQueue::currencyType)
_CLASSREGISTER_AddVar(state, ProductQueue::state)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(ProductRecipe)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(productId, ProductRecipe::productId)
_CLASSREGISTER_AddVar(needLevel, ProductRecipe::needLevel)
_CLASSREGISTER_AddVar(needTime, ProductRecipe::needTime)
_CLASSREGISTER_AddVar(items, ProductRecipe::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchOrderInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(index, RanchOrderInfo::index)
_CLASSREGISTER_AddVar(itemId, RanchOrderInfo::itemId)
_CLASSREGISTER_AddVar(needNum, RanchOrderInfo::needNum)
_CLASSREGISTER_AddVar(helperId, RanchOrderInfo::helperId)
_CLASSREGISTER_AddVar(isDone, RanchOrderInfo::isDone)
_CLASSREGISTER_AddVar(isHelp, RanchOrderInfo::isHelp)
_CLASSREGISTER_AddVar(isHot, RanchOrderInfo::isHot)
_CLASSREGISTER_AddVar(helperSex, RanchOrderInfo::helperSex)
_CLASSREGISTER_AddVar(fullBoxNum, RanchOrderInfo::fullBoxNum)
_CLASSREGISTER_AddVar(boxAmount, RanchOrderInfo::boxAmount)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchOrder)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchOrder::id)
_CLASSREGISTER_AddVar(price, RanchOrder::price)
_CLASSREGISTER_AddVar(status, RanchOrder::status)
_CLASSREGISTER_AddVar(timeLeft, RanchOrder::timeLeft)
_CLASSREGISTER_AddVar(refreshTimeLeft, RanchOrder::refreshTimeLeft)
_CLASSREGISTER_AddVar(msg, RanchOrder::msg)
_CLASSREGISTER_AddVar(guestIcon, RanchOrder::guestIcon)
_CLASSREGISTER_AddVar(isHot, RanchOrder::isHot)
_CLASSREGISTER_AddVar(infos, RanchOrder::infos)
_CLASSREGISTER_AddVar(rewards, RanchOrder::rewards)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchAchievement)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchAchievement::id)
_CLASSREGISTER_AddVar(exp, RanchAchievement::exp)
_CLASSREGISTER_AddVar(level, RanchAchievement::level)
_CLASSREGISTER_AddVar(nextExp, RanchAchievement::nextExp)
_CLASSREGISTER_AddVar(maxLevel, RanchAchievement::maxLevel)
_CLASSREGISTER_AddVar(playerExp, RanchAchievement::playerExp)
_CLASSREGISTER_AddVar(achievement, RanchAchievement::achievement)
_CLASSREGISTER_AddVar(icon, RanchAchievement::icon)
_CLASSREGISTER_AddVar(desc, RanchAchievement::desc)
_CLASSREGISTER_AddVar(name, RanchAchievement::name)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(RanchTimePrice)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, RanchTimePrice::id)
_CLASSREGISTER_AddVar(price, RanchTimePrice::price)
_CLASSREGISTER_AddVar(timeLeft, RanchTimePrice::timeLeft)
_END_REGISTER_CLASS()


// Register Class BirdSimulator
_BEGIN_REGISTER_CLASS(BirdSimulator)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(setBag, BirdSimulator::setBag)
_CLASSREGISTER_AddMember(setActivity, BirdSimulator::setActivity)
_CLASSREGISTER_AddMember(setPlayerInfo, BirdSimulator::setPlayerInfo)
_CLASSREGISTER_AddMember(setAtlas, BirdSimulator::setAtlasFromLua)
_CLASSREGISTER_AddMember(setTasks, BirdSimulator::setTasksFromLua)
_CLASSREGISTER_AddMember(setDress, BirdSimulator::setDressFromLua)
_CLASSREGISTER_AddMember(setFoods, BirdSimulator::setFoodsFromLua)
_CLASSREGISTER_AddMember(setStores, BirdSimulator::setStoresFromLua)
_CLASSREGISTER_AddMember(setPersonalStore, BirdSimulator::setPersonalStoreFromLua)
_CLASSREGISTER_AddMember(setScopes, BirdSimulator::setScopesFromLua)
_CLASSREGISTER_AddMember(setTimePrices, BirdSimulator::setTimePricesFromLua)
_CLASSREGISTER_AddMember(setBuffs, BirdSimulator::setBuffsFromLua)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdStore)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdStore::id)
_CLASSREGISTER_AddVar(startPos, BirdStore::startPos)
_CLASSREGISTER_AddVar(endPos, BirdStore::endPos)
_CLASSREGISTER_AddVar(items, BirdStore::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdStoreItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdStoreItem::id)
_CLASSREGISTER_AddVar(storeId, BirdStoreItem::storeId)
_CLASSREGISTER_AddVar(price, BirdStoreItem::price)
_CLASSREGISTER_AddVar(currencyType, BirdStoreItem::currencyType)
_CLASSREGISTER_AddVar(status, BirdStoreItem::status)
_CLASSREGISTER_AddVar(type, BirdStoreItem::type)
_CLASSREGISTER_AddVar(name, BirdStoreItem::name)
_CLASSREGISTER_AddVar(desc, BirdStoreItem::desc)
_CLASSREGISTER_AddVar(icon, BirdStoreItem::icon)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdGiftBagItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdGiftBagItem::id)
_CLASSREGISTER_AddVar(num, BirdGiftBagItem::num)
_CLASSREGISTER_AddVar(type, BirdGiftBagItem::type)
_CLASSREGISTER_AddVar(icon, BirdGiftBagItem::icon)
_CLASSREGISTER_AddVar(giftBagId, BirdGiftBagItem::giftBagId)
_CLASSREGISTER_AddVar(isAutoUse, BirdGiftBagItem::isAutoUse)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdGiftBag)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdGiftBag::id)
_CLASSREGISTER_AddVar(price, BirdGiftBag::price)
_CLASSREGISTER_AddVar(limit, BirdGiftBag::limit)
_CLASSREGISTER_AddVar(timeLeft, BirdGiftBag::timeLeft)
_CLASSREGISTER_AddVar(discount, BirdGiftBag::discount)
_CLASSREGISTER_AddVar(currencyType, BirdGiftBag::currencyType)
_CLASSREGISTER_AddVar(icon, BirdGiftBag::icon)
_CLASSREGISTER_AddVar(desc, BirdGiftBag::desc)
_CLASSREGISTER_AddVar(name, BirdGiftBag::name)
_CLASSREGISTER_AddVar(topLeftIcon, BirdGiftBag::topLeftIcon)
_CLASSREGISTER_AddVar(topLeftName, BirdGiftBag::topLeftName)
_CLASSREGISTER_AddVar(topRightIcon, BirdGiftBag::topRightIcon)
_CLASSREGISTER_AddVar(topRightName, BirdGiftBag::topRightName)
_CLASSREGISTER_AddVar(items, BirdGiftBag::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdPersonalStoreTab)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(tabId, BirdPersonalStoreTab::tabId)
_CLASSREGISTER_AddVar(tabName, BirdPersonalStoreTab::tabName)
_CLASSREGISTER_AddVar(tabIcon, BirdPersonalStoreTab::tabIcon)
_CLASSREGISTER_AddVar(items, BirdPersonalStoreTab::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdDress)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdDress::id)
_CLASSREGISTER_AddVar(num, BirdDress::num)
_CLASSREGISTER_AddVar(type, BirdDress::type)
_CLASSREGISTER_AddVar(isUse, BirdDress::isUse)
_CLASSREGISTER_AddVar(bodyId, BirdDress::bodyId)
_CLASSREGISTER_AddVar(bodyName, BirdDress::bodyName)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdInfo::id)
_CLASSREGISTER_AddVar(level, BirdInfo::level)
_CLASSREGISTER_AddVar(maxLevel, BirdInfo::maxLevel)
_CLASSREGISTER_AddVar(exp, BirdInfo::exp)
_CLASSREGISTER_AddVar(nextExp, BirdInfo::nextExp)
_CLASSREGISTER_AddVar(quality, BirdInfo::quality)
_CLASSREGISTER_AddVar(speed, BirdInfo::speed)
_CLASSREGISTER_AddVar(gather, BirdInfo::gather)
_CLASSREGISTER_AddVar(conver, BirdInfo::conver)
_CLASSREGISTER_AddVar(attack, BirdInfo::attack)
_CLASSREGISTER_AddVar(isCarry, BirdInfo::isCarry)
_CLASSREGISTER_AddVar(name, BirdInfo::name)
_CLASSREGISTER_AddVar(icon, BirdInfo::icon)
_CLASSREGISTER_AddVar(skill, BirdInfo::skill)
_CLASSREGISTER_AddVar(talent, BirdInfo::talent)
_CLASSREGISTER_AddVar(glassesId, BirdInfo::glassesId)
_CLASSREGISTER_AddVar(hatId, BirdInfo::hatId)
_CLASSREGISTER_AddVar(beakId, BirdInfo::beakId)
_CLASSREGISTER_AddVar(wingId, BirdInfo::wingId)
_CLASSREGISTER_AddVar(tailId, BirdInfo::tailId)
_CLASSREGISTER_AddVar(effectId, BirdInfo::effectId)
_CLASSREGISTER_AddVar(bodyId, BirdInfo::bodyId)
_CLASSREGISTER_AddVar(convertTime, BirdInfo::convertTime)
_CLASSREGISTER_AddVar(gatherTime, BirdInfo::gatherTime)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdBag)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(curCarry, BirdBag::curCarry)
_CLASSREGISTER_AddVar(maxCarry, BirdBag::maxCarry)
_CLASSREGISTER_AddVar(curCapacity, BirdBag::curCapacity)
_CLASSREGISTER_AddVar(maxCapacity, BirdBag::maxCapacity)
_CLASSREGISTER_AddVar(maxCarryLevel, BirdBag::maxCarryLevel)
_CLASSREGISTER_AddVar(maxCapacityLevel, BirdBag::maxCapacityLevel)
_CLASSREGISTER_AddVar(expandCarryPrice, BirdBag::expandCarryPrice)
_CLASSREGISTER_AddVar(expandCapacityPrice, BirdBag::expandCapacityPrice)
_CLASSREGISTER_AddVar(expandCurrencyType, BirdBag::expandCurrencyType)
_CLASSREGISTER_AddVar(birds, BirdBag::birds)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdPlayerInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(score, BirdPlayerInfo::score)
_CLASSREGISTER_AddVar(eggTicket, BirdPlayerInfo::eggTicket)
_CLASSREGISTER_AddVar(isConvert, BirdPlayerInfo::isConvert)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdFood)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdFood::id)
_CLASSREGISTER_AddVar(num, BirdFood::num)
_CLASSREGISTER_AddVar(name, BirdFood::name)
_CLASSREGISTER_AddVar(icon, BirdFood::icon)
_CLASSREGISTER_AddVar(desc, BirdFood::desc)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdTaskItem)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdTaskItem::id)
_CLASSREGISTER_AddVar(curValue, BirdTaskItem::curValue)
_CLASSREGISTER_AddVar(needValue, BirdTaskItem::needValue)
_CLASSREGISTER_AddVar(desc, BirdTaskItem::desc)
_CLASSREGISTER_AddVar(name, BirdTaskItem::name)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdTask)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(taskId, BirdTask::taskId)
_CLASSREGISTER_AddVar(curValue, BirdTask::entityId)
_CLASSREGISTER_AddVar(taskName, BirdTask::taskName)
_CLASSREGISTER_AddVar(contents, BirdTask::contents)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdEgg)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdEgg::id)
_CLASSREGISTER_AddVar(quality, BirdEgg::quality)
_CLASSREGISTER_AddVar(icon, BirdEgg::icon)
_CLASSREGISTER_AddVar(isHave, BirdEgg::isHave)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdAtlas)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdAtlas::id)
_CLASSREGISTER_AddVar(eggIcon, BirdAtlas::eggIcon)
_CLASSREGISTER_AddVar(items, BirdAtlas::items)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdGain)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(itemId, BirdGain::itemId)
_CLASSREGISTER_AddVar(icon, BirdGain::icon)
_CLASSREGISTER_AddVar(num, BirdGain::num)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdScope)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdScope::id)
_CLASSREGISTER_AddVar(type, BirdScope::type)
_CLASSREGISTER_AddVar(startPos, BirdScope::startPos)
_CLASSREGISTER_AddVar(endPos, BirdScope::endPos)
_END_REGISTER_CLASS()


_BEGIN_REGISTER_CLASS(BirdTimePrice)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdTimePrice::id)
_CLASSREGISTER_AddVar(price, BirdTimePrice::price)
_CLASSREGISTER_AddVar(timeLeft, BirdTimePrice::timeLeft)
_END_REGISTER_CLASS()

_BEGIN_REGISTER_CLASS(BirdBuff)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddVar(id, BirdBuff::id)
_CLASSREGISTER_AddVar(level, BirdBuff::level)
_CLASSREGISTER_AddVar(icon, BirdBuff::icon)
_CLASSREGISTER_AddVar(timeLeft, BirdBuff::timeLeft)
_END_REGISTER_CLASS()