#include "Chunk/Chunk.h"
#include "World/ChunkCollection.h"
#include "World/GameSettings.h"
#include "World/IBlockAccess.h"
#include "World/IWorldEventListener.h"
#include "World/NibbleArray.h"
#include "Chunk/RangeChunkCache.h"
#include "World/RayTracyResult.h"
#include "World/Section.h"
#include "World/TickEntry.h"
#include "World/World.h"
#include "World/WorldChunkManager.h"
#include "World/WorldInfo.h"
#include "World/WorldProvider.h"
#include "World/WorldSettings.h"
#include "World/Shop.h"
#include "Block/BM_Material.h"
#include "LuaRegister/Template/LuaRegister.h"
using namespace BLOCKMAN;

using namespace LUA_REGISTER;


// Register Class Chunk
_BEGIN_REGISTER_CLASS(Chunk)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddCtor(World * , int , int )
_CLASSREGISTER_AddMember(addEntity, Chunk::addEntity)
_CLASSREGISTER_AddMember(addTileEntity, Chunk::addTileEntity)
_CLASSREGISTER_AddMember(canBlockSeeTheSky, Chunk::canBlockSeeTheSky)
_CLASSREGISTER_AddMember(fillChunk, Chunk::fillChunk)
_CLASSREGISTER_AddMember(gapLightingUpdated, Chunk::gapLightingUpdated)
_CLASSREGISTER_AddMember(generateHeightMap, Chunk::generateHeightMap)
_CLASSREGISTER_AddMember(generateSkylightMap, Chunk::generateSkylightMap)
_CLASSREGISTER_AddMember(getAreLevelsEmpty, Chunk::getAreLevelsEmpty)
_CLASSREGISTER_AddMember(getBiomeArray, Chunk::getBiomeArray)
_CLASSREGISTER_AddMember(getBiomeGenForWorldCoords, Chunk::getBiomeGenForWorldCoords)
_CLASSREGISTER_AddMember(getBlockID, Chunk::getBlockID)
_CLASSREGISTER_AddMember(getBlockIDAndMeta, Chunk::getBlockIDAndMeta)
_CLASSREGISTER_AddMember(getBlockLightOpacity, Chunk::getBlockLightOpacity)
_CLASSREGISTER_AddMember(getBlockLightValue, Chunk::getBlockLightValue)
_CLASSREGISTER_AddMember(getBlockMeta, Chunk::getBlockMeta)
_CLASSREGISTER_AddMember(getChunkBlockTileEntity, Chunk::getChunkBlockTileEntity)
_CLASSREGISTER_AddMember(getChunkCoordIntPair, Chunk::getChunkCoordIntPair)
_CLASSREGISTER_AddMember(getEntitiesWithinAABB, Chunk::getEntitiesWithinAABB)
_CLASSREGISTER_AddMember(getEntitiesWithinAABBForEntity, Chunk::getEntitiesWithinAABBForEntity)
_CLASSREGISTER_AddMember(getHeightValue, Chunk::getHeightValue)
_CLASSREGISTER_AddMember(getMinimumHeight, Chunk::getMinimumHeight)
_CLASSREGISTER_AddMember(getPrecipitationHeight, Chunk::getPrecipitationHeight)
_CLASSREGISTER_AddMember(getRandomWithSeed, Chunk::getRandomWithSeed)
_CLASSREGISTER_AddMember(getSavedLightValue, Chunk::getSavedLightValue)
_CLASSREGISTER_AddMember(getSectionArray, Chunk::getSectionArray)
_CLASSREGISTER_AddMember(getTopFilledSegment, Chunk::getTopFilledSegment)
_CLASSREGISTER_AddMember(isAtLocation, Chunk::isAtLocation)
_CLASSREGISTER_AddMember(isNonexistent, Chunk::isNonexistent)
_CLASSREGISTER_AddMember(needsSaving, Chunk::needsSaving)
_CLASSREGISTER_AddMember(onChunkLoad, Chunk::onChunkLoad)
_CLASSREGISTER_AddMember(onChunkUnload, Chunk::onChunkUnload)
_CLASSREGISTER_AddMember(reBuildVisibility, Chunk::reBuildVisibility)
_CLASSREGISTER_AddMember(relightBlockLight, Chunk::relightBlockLight)
_CLASSREGISTER_AddMember(removeChunkBlockTileEntity, Chunk::removeChunkBlockTileEntity)
_CLASSREGISTER_AddMember(removeEntity, Chunk::removeEntity)
_CLASSREGISTER_AddMember(removeEntityAtIndex, Chunk::removeEntityAtIndex)
_CLASSREGISTER_AddMember(resetPrecipitation, Chunk::resetPrecipitation)
_CLASSREGISTER_AddMember(resetRelightChecks, Chunk::resetRelightChecks)
_CLASSREGISTER_AddMember(setBlockIDAndMeta, Chunk::setBlockIDAndMeta)
_CLASSREGISTER_AddMember(setBlockMeta, Chunk::setBlockMeta)
_CLASSREGISTER_AddMember(setChunkBlockTileEntity, Chunk::setChunkBlockTileEntity)
_CLASSREGISTER_AddMember(setChunkModified, Chunk::setChunkModified)
_CLASSREGISTER_AddMember(setData, Chunk::setData)
_CLASSREGISTER_AddMember(setLightValue, Chunk::setLightValue)
_CLASSREGISTER_AddMember(setSectionXZ, Chunk::setSectionXZ)
_CLASSREGISTER_AddMember(toAbsoluteBlockPos, Chunk::toAbsoluteBlockPos)
_CLASSREGISTER_AddMember(updateBlocklight, Chunk::updateBlocklight)
_CLASSREGISTER_AddMember(updateHeightMap, Chunk::updateHeightMap)
_CLASSREGISTER_AddMember(updateSkylight, Chunk::updateSkylight)
_END_REGISTER_CLASS()


// Register Class ChunkCollection
_BEGIN_REGISTER_CLASS(ChunkCollection)
_CLASSREGISTER_AddBaseClass(IBlockAccess)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(World * , const BlockPos & , const BlockPos & , int )
_CLASSREGISTER_AddMember(doesBlockHaveSolidTopSurface, ChunkCollection::doesBlockHaveSolidTopSurface)
_CLASSREGISTER_AddMember(extendedLevelsInChunkCollection, ChunkCollection::extendedLevelsInChunkCollection)
_CLASSREGISTER_AddMember(getBiomeGenForCoords, ChunkCollection::getBiomeGenForCoords)
_CLASSREGISTER_AddMember(getBlockIDAndMeta, ChunkCollection::getBlockIDAndMeta)
_CLASSREGISTER_AddMember(getBlockId, ChunkCollection::getBlockId)
_CLASSREGISTER_AddMember(getBlockMaterial, ChunkCollection::getBlockMaterial)
_CLASSREGISTER_AddMember(getBlockMeta, ChunkCollection::getBlockMeta)
_CLASSREGISTER_AddMember(getBlockTileEntity, ChunkCollection::getBlockTileEntity)
_CLASSREGISTER_AddMember(getBrightness, ChunkCollection::getBrightness)
_CLASSREGISTER_AddMember(getHeight, ChunkCollection::getHeight)
_CLASSREGISTER_AddMember(getLightBrightness, ChunkCollection::getLightBrightness)
_CLASSREGISTER_AddMember(getLightBrightnessForSkyBlocks, ChunkCollection::getLightBrightnessForSkyBlocks)
_CLASSREGISTER_AddMember(getLightValue, ChunkCollection::getLightValue)
_CLASSREGISTER_AddMember(getLightValueExt, ChunkCollection::getLightValueExt)
_CLASSREGISTER_AddMember(getSkyBlockTypeBrightness, ChunkCollection::getSkyBlockTypeBrightness)
_CLASSREGISTER_AddMember(getSpecialBlockBrightness, ChunkCollection::getSpecialBlockBrightness)
_CLASSREGISTER_AddMember(isAirBlock, ChunkCollection::isAirBlock)
_CLASSREGISTER_AddMember(isBlockNormalCube, ChunkCollection::isBlockNormalCube)
_CLASSREGISTER_AddMember(isBlockOpaqueCube, ChunkCollection::isBlockOpaqueCube)
_CLASSREGISTER_AddMember(isBlockProvidingPowerTo, ChunkCollection::isBlockProvidingPowerTo)
_CLASSREGISTER_AddMember(isInAsync, ChunkCollection::isInAsync)
_END_REGISTER_CLASS()




// Register Class GameSettings
_BEGIN_REGISTER_CLASS(GameSettings)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddMember(beginMouseMove, GameSettings::beginMouseMove)
_CLASSREGISTER_AddMember(endMouseMove, GameSettings::endMouseMove)
_CLASSREGISTER_AddMember(getDetectChunksRange, GameSettings::getDetectChunksRange)
_CLASSREGISTER_AddMember(getKeyBindingDescription, GameSettings::getKeyBindingDescription)
_CLASSREGISTER_AddStaticMember(getKeyDisplayString, GameSettings::getKeyDisplayString)
_CLASSREGISTER_AddMember(getLoadChunksRange, GameSettings::getLoadChunksRange)
_CLASSREGISTER_AddMember(getOptionDisplayString, GameSettings::getOptionDisplayString)
_CLASSREGISTER_AddMember(getRenderChunksRange, GameSettings::getRenderChunksRange)
_CLASSREGISTER_AddMember(setKeyBinding, GameSettings::setKeyBinding)
_CLASSREGISTER_AddMember(setMousePos, GameSettings::setMousePos)
_CLASSREGISTER_AddMember(shouldRenderClouds, GameSettings::shouldRenderClouds)
_END_REGISTER_CLASS()




// Register Class KeyBinding
_BEGIN_REGISTER_CLASS(KeyBinding)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(const String & , int )
_CLASSREGISTER_AddStaticMember(getKeyBinding, KeyBinding::getKeyBinding)
_CLASSREGISTER_AddMember(isPressed, KeyBinding::isPressed)
_CLASSREGISTER_AddStaticMember(onTick, KeyBinding::onTick)
_CLASSREGISTER_AddStaticMember(resetKeyBindingArrayAndHash, KeyBinding::resetKeyBindingArrayAndHash)
_CLASSREGISTER_AddStaticMember_Override(setKeyBindState, KeyBinding::setKeyBindState,void ,int ,bool )
_CLASSREGISTER_AddStaticMember_Override(setKeyBindState1, KeyBinding::setKeyBindState,void ,const String & ,bool )
_CLASSREGISTER_AddMember(setKeyState, KeyBinding::setKeyState)
_CLASSREGISTER_AddStaticMember(unPressAllKeys, KeyBinding::unPressAllKeys)
_CLASSREGISTER_AddMember(unpressKey, KeyBinding::unpressKey)
_END_REGISTER_CLASS()




// Register Class IBlockAccess
_BEGIN_REGISTER_CLASS(IBlockAccess)
_CLASSREGISTER_AddMember(getHeight, IBlockAccess::getHeight)
_END_REGISTER_CLASS()






// Register Class NibbleArray
_BEGIN_REGISTER_CLASS(NibbleArray)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(int , int )
_CLASSREGISTER_AddCtor(i8 * , int , int )
_CLASSREGISTER_AddMember(bytes, NibbleArray::bytes)
_CLASSREGISTER_AddMember(clear, NibbleArray::clear)
_CLASSREGISTER_AddMember_Override(get, NibbleArray::get,int ,int ,int ,int )
_CLASSREGISTER_AddMember_Override(get1, NibbleArray::get,int ,const Vector3i & )
_CLASSREGISTER_AddMember(resize, NibbleArray::resize)
_CLASSREGISTER_AddMember_Override(set, NibbleArray::set,void ,int ,int ,int ,int )
_CLASSREGISTER_AddMember_Override(set1, NibbleArray::set,void ,const Vector3i & ,int )
_END_REGISTER_CLASS()




// Register Class RayTraceResult
_BEGIN_REGISTER_CLASS(RayTraceResult)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddStaticMember(calculateIntercept, RayTraceResult::calculateIntercept)
_CLASSREGISTER_AddMember(getBlockPos, RayTraceResult::getBlockPos)
_CLASSREGISTER_AddMember(reset, RayTraceResult::reset)
_CLASSREGISTER_AddMember_Override(set, RayTraceResult::set,void ,const Vector3 & ,Facing * ,const Vector3i & )
_CLASSREGISTER_AddMember_Override(set1, RayTraceResult::set,void ,const Vector3 & ,Facing * )
_CLASSREGISTER_AddMember_Override(set2, RayTraceResult::set,void ,Entity * )
_CLASSREGISTER_AddMember_Override(set3, RayTraceResult::set,void ,RAYTRACE_TYPE ,const Vector3 & ,Facing * ,const Vector3i & )
_CLASSREGISTER_AddMember_Override(set4, RayTraceResult::set,void ,Entity * ,const Vector3 & )
_CLASSREGISTER_AddMember(toString, RayTraceResult::toString)
_END_REGISTER_CLASS()




// Register Class Section
_BEGIN_REGISTER_CLASS(Section)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(int )
_CLASSREGISTER_AddMember(blockRefCount, Section::blockRefCount)
_CLASSREGISTER_AddMember(getBlockID, Section::getBlockID)
_CLASSREGISTER_AddMember(getBlockMeta, Section::getBlockMeta)
_CLASSREGISTER_AddMember(getExtBlocklightValue, Section::getExtBlocklightValue)
_CLASSREGISTER_AddMember(getExtSkylightValue, Section::getExtSkylightValue)
_CLASSREGISTER_AddMember(getMetadataArray, Section::getMetadataArray)
_CLASSREGISTER_AddMember(getNeedsRandomTick, Section::getNeedsRandomTick)
_CLASSREGISTER_AddMember(getVisibility, Section::getVisibility)
_CLASSREGISTER_AddMember(getYLocation, Section::getYLocation)
_CLASSREGISTER_AddMember(isEmpty, Section::isEmpty)
_CLASSREGISTER_AddMember(reBuildVisibility, Section::reBuildVisibility)
_CLASSREGISTER_AddMember(removeInvalidBlocks, Section::removeInvalidBlocks)
_CLASSREGISTER_AddMember(setBlockID, Section::setBlockID)
_CLASSREGISTER_AddMember(setBlockMeta, Section::setBlockMeta)
_CLASSREGISTER_AddMember(setExtBlocklightValue, Section::setExtBlocklightValue)
_CLASSREGISTER_AddMember(setExtSkylightValue, Section::setExtSkylightValue)
_CLASSREGISTER_AddMember(setPosXZ, Section::setPosXZ)
_CLASSREGISTER_AddMember(tickRefCount, Section::tickRefCount)
_END_REGISTER_CLASS()




// Register Class World
_BEGIN_REGISTER_CLASS(World)
_CLASSREGISTER_AddBaseClass(IBlockAccess)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddMember(setTimeStopped, World::setTimeStopped)
_CLASSREGISTER_AddMember(addBlockEvent, World::addBlockEvent)
_CLASSREGISTER_AddMember(addWorldListener, World::addWorldListener)
_CLASSREGISTER_AddMember(blockExists, World::blockExists)
_CLASSREGISTER_AddMember(blockHasTileEntity, World::blockHasTileEntity)
_CLASSREGISTER_AddMember(calculateInitialSkylight, World::calculateInitialSkylight)
_CLASSREGISTER_AddMember(calculateSkylightSubtracted, World::calculateSkylightSubtracted)
_CLASSREGISTER_AddMember(canBlockFreeze, World::canBlockFreeze)
_CLASSREGISTER_AddMember(canBlockSeeTheSky, World::canBlockSeeTheSky)
_CLASSREGISTER_AddMember(canLightningStrikeAt, World::canLightningStrikeAt)
_CLASSREGISTER_AddMember(canMineBlock, World::canMineBlock)
_CLASSREGISTER_AddMember(canPlaceEntityOnSide, World::canPlaceEntityOnSide)
_CLASSREGISTER_AddMember(canSnowAt, World::canSnowAt)
_CLASSREGISTER_AddMember(checkBlockCollision, World::checkBlockCollision)
_CLASSREGISTER_AddMember(checkChunksExist, World::checkChunksExist)
_CLASSREGISTER_AddMember_Override(checkNoEntityCollision, World::checkNoEntityCollision,bool ,const Box & )
_CLASSREGISTER_AddMember_Override(checkNoEntityCollision1, World::checkNoEntityCollision,bool ,const Box & ,Entity * )
_CLASSREGISTER_AddMember(chunkExists, World::chunkExists)
_CLASSREGISTER_AddMember(createExplosion, World::createExplosion)
_CLASSREGISTER_AddMember(destroyBlock, World::destroyBlock)
_CLASSREGISTER_AddMember(destroyBlockInWorldPartially, World::destroyBlockInWorldPartially)
_CLASSREGISTER_AddMember(doChunksNearChunkExist, World::doChunksNearChunkExist)
_CLASSREGISTER_AddMember(doesBlockHaveSolidTopSurface, World::doesBlockHaveSolidTopSurface)
_CLASSREGISTER_AddMember(extendedLevelsInChunkCollection, World::extendedLevelsInChunkCollection)
_CLASSREGISTER_AddMember(extinguishFire, World::extinguishFire)
_CLASSREGISTER_AddMember(getActualHeight, World::getActualHeight)
_CLASSREGISTER_AddMember(getBiomeGenForCoords, World::getBiomeGenForCoords)
_CLASSREGISTER_AddMember(getBlockDensity, World::getBlockDensity)
_CLASSREGISTER_AddMember(getBlockIDAndMeta, World::getBlockIDAndMeta)
_CLASSREGISTER_AddMember(getBlockId, World::getBlockId)
_CLASSREGISTER_AddMember(getBlockLightValue, World::getBlockLightValue)
_CLASSREGISTER_AddMember(getBlockMaterial, World::getBlockMaterial)
_CLASSREGISTER_AddMember(getBlockMeta, World::getBlockMeta)
_CLASSREGISTER_AddMember(getBlockPowerInput, World::getBlockPowerInput)
_CLASSREGISTER_AddMember(getBlockTileEntity, World::getBlockTileEntity)
_CLASSREGISTER_AddMember(getBrightness, World::getBrightness)
_CLASSREGISTER_AddMember(getCelestialAngle, World::getCelestialAngle)
_CLASSREGISTER_AddMember(getCelestialAngleRadians, World::getCelestialAngleRadians)
_CLASSREGISTER_AddMember(getChunkFromBlockCoords, World::getChunkFromBlockCoords)
_CLASSREGISTER_AddMember(getChunkFromChunkCoords, World::getChunkFromChunkCoords)
_CLASSREGISTER_AddMember(getChunkHeightMapMinimum, World::getChunkHeightMapMinimum)
_CLASSREGISTER_AddMember(getChunkService, World::getChunkService)
_CLASSREGISTER_AddMember(getClosestPlayer, World::getClosestPlayer)
_CLASSREGISTER_AddMember(getClosestPlayerToEntity, World::getClosestPlayerToEntity)
_CLASSREGISTER_AddMember(getClosestVulnerablePlayer, World::getClosestVulnerablePlayer)
_CLASSREGISTER_AddMember(getClosestVulnerablePlayerToEntity, World::getClosestVulnerablePlayerToEntity)
_CLASSREGISTER_AddMember(getCollidingBlockBounds, World::getCollidingBlockBounds)
_CLASSREGISTER_AddMember(getCollidingBoundingBoxes, World::getCollidingBoundingBoxes)
_CLASSREGISTER_AddMember(getEntitiesWithinAABB, World::getEntitiesWithinAABB)
_CLASSREGISTER_AddMember(getEntitiesWithinAABBExcludingEntity, World::getEntitiesWithinAABBExcludingEntity)
_CLASSREGISTER_AddMember(getEntity, World::getEntity)
_CLASSREGISTER_AddMember(getEntityPathToXYZ, World::getEntityPathToXYZ)
_CLASSREGISTER_AddMember(getFirstUncoveredBlock, World::getFirstUncoveredBlock)
_CLASSREGISTER_AddMember(getFullBlockLightValue, World::getFullBlockLightValue)
_CLASSREGISTER_AddMember(getHeight, World::getHeight)
_CLASSREGISTER_AddMember(getHeightValue, World::getHeightValue)
_CLASSREGISTER_AddMember(getHorizon, World::getHorizon)
_CLASSREGISTER_AddMember(getIndirectPowerLevelTo, World::getIndirectPowerLevelTo)
_CLASSREGISTER_AddMember(getIndirectPowerOutput, World::getIndirectPowerOutput)
_CLASSREGISTER_AddMember(getLightBrightness, World::getLightBrightness)
_CLASSREGISTER_AddMember(getLightBrightnessForSkyBlocks, World::getLightBrightnessForSkyBlocks)
_CLASSREGISTER_AddMember(getLoadedEntityMap, World::getLoadedEntityMap)
_CLASSREGISTER_AddMember(getPathEntityToEntity, World::getPathEntityToEntity)
_CLASSREGISTER_AddMember(getPlayerEntity, World::getPlayerEntity)
_CLASSREGISTER_AddMember(getPlayers, World::getPlayers)
_CLASSREGISTER_AddMember(getPrecipitationHeight, World::getPrecipitationHeight)
_CLASSREGISTER_AddMember(getSavedLightValue, World::getSavedLightValue)
_CLASSREGISTER_AddMember(getSeed, World::getSeed)
_CLASSREGISTER_AddMember(getSkyBlockTypeBrightness, World::getSkyBlockTypeBrightness)
_CLASSREGISTER_AddMember(getSpawnPoint, World::getSpawnPoint)
_CLASSREGISTER_AddMember(getStrongestIndirectPower, World::getStrongestIndirectPower)
_CLASSREGISTER_AddMember(getTopSolidOrLiquidBlock, World::getTopSolidOrLiquidBlock)
_CLASSREGISTER_AddMember(getTotalWorldTime, World::getTotalWorldTime)
_CLASSREGISTER_AddMember(getUniqueDataId, World::getUniqueDataId)
_CLASSREGISTER_AddMember(getWorldChunkManager, World::getWorldChunkManager)
_CLASSREGISTER_AddMember(getWorldInfo, World::getWorldInfo)
_CLASSREGISTER_AddMember(getWorldTime, World::getWorldTime)
_CLASSREGISTER_AddMember(handleMaterialAcceleration, World::handleMaterialAcceleration)
_CLASSREGISTER_AddMember(init, World::init)
_CLASSREGISTER_AddMember(initialize, World::initialize)
_CLASSREGISTER_AddMember(isAirBlock, World::isAirBlock)
_CLASSREGISTER_AddMember(isAnyLiquid, World::isAnyLiquid)
_CLASSREGISTER_AddMember(isBlockFreezable, World::isBlockFreezable)
_CLASSREGISTER_AddMember(isBlockFullCube, World::isBlockFullCube)
_CLASSREGISTER_AddMember(isBlockHighHumidity, World::isBlockHighHumidity)
_CLASSREGISTER_AddMember(isBlockIndirectlyGettingPowered, World::isBlockIndirectlyGettingPowered)
_CLASSREGISTER_AddMember(isBlockNormalCube, World::isBlockNormalCube)
_CLASSREGISTER_AddMember(isBlockNormalCubeDefault, World::isBlockNormalCubeDefault)
_CLASSREGISTER_AddMember(isBlockOpaqueCube, World::isBlockOpaqueCube)
_CLASSREGISTER_AddMember(isBlockProvidingPowerTo, World::isBlockProvidingPowerTo)
_CLASSREGISTER_AddMember(isBlockTickScheduledThisTick, World::isBlockTickScheduledThisTick)
_CLASSREGISTER_AddMember(isBlockTopFacingSurfaceSolid, World::isBlockTopFacingSurfaceSolid)
_CLASSREGISTER_AddMember(isBoundingBoxBurning, World::isBoundingBoxBurning)
_CLASSREGISTER_AddMember(isDaytime, World::isDaytime)
_CLASSREGISTER_AddMember(isMaterialInBB, World::isMaterialInBB)
_CLASSREGISTER_AddMember(markBlockForRenderUpdate, World::markBlockForRenderUpdate)
_CLASSREGISTER_AddMember(markBlockForUpdate, World::markBlockForUpdate)
_CLASSREGISTER_AddMember(markBlockRangeForRenderUpdate, World::markBlockRangeForRenderUpdate)
_CLASSREGISTER_AddMember(markBlocksDirtyVertical, World::markBlocksDirtyVertical)
_CLASSREGISTER_AddMember(markTileEntityForDespawn, World::markTileEntityForDespawn)
_CLASSREGISTER_AddMember(newExplosion, World::newExplosion)
_CLASSREGISTER_AddMember(notifyBlockChange, World::notifyBlockChange)
_CLASSREGISTER_AddMember(notifyBlockOfNeighborChange, World::notifyBlockOfNeighborChange)
_CLASSREGISTER_AddMember_Override(notifyBlocksOfNeighborChange, World::notifyBlocksOfNeighborChange, void, const BlockPos &, int)
_CLASSREGISTER_AddMember_Override(notifyBlocksOfNeighborChange1, World::notifyBlocksOfNeighborChange, void, const BlockPos &, int, int)
_CLASSREGISTER_AddMember(playAuxSFX, World::playAuxSFX)
_CLASSREGISTER_AddMember(playAuxSFXAtEntity, World::playAuxSFXAtEntity)
_CLASSREGISTER_AddMember(playRecord, World::playRecord)
_CLASSREGISTER_AddMember(playSoundByType, World::playSoundByType)
_CLASSREGISTER_AddMember(playSoundAtEntityByType, World::playSoundAtEntityByType)
_CLASSREGISTER_AddMember(playSoundEffect, World::playSoundEffectByType)
_CLASSREGISTER_AddMember(playSoundOfPlaceBlock, World::playSoundOfPlaceBlock)
_CLASSREGISTER_AddMember(playSoundOfStepOnBlock, World::playSoundOfStepOnBlock)
_CLASSREGISTER_AddMember(playSoundToNearExceptByType, World::playSoundToNearExceptByType)
_CLASSREGISTER_AddMember_Override(rayTraceBlocks, World::rayTraceBlocks, RayTraceResult, Vector3, Vector3)
_CLASSREGISTER_AddMember_Override(rayTraceBlocks1, World::rayTraceBlocks, RayTraceResult, Vector3, Vector3, bool)
_CLASSREGISTER_AddMember_Override(rayTraceBlocks2, World::rayTraceBlocks, RayTraceResult, Vector3, Vector3, bool, bool)
_CLASSREGISTER_AddMember(removeBlockTileEntity, World::removeBlockTileEntity)
_CLASSREGISTER_AddMember_Override(removeEntity, World::removeEntity, void, Entity *)
_CLASSREGISTER_AddMember_Override(removeEntity1, World::removeEntity, void, int)
_CLASSREGISTER_AddMember(removePlayerEntityDangerously, World::removePlayerEntityDangerously)
_CLASSREGISTER_AddMember(removeWorldListener, World::removeWorldListener)
_CLASSREGISTER_AddMember(scheduleBlockUpdate, World::scheduleBlockUpdate)
_CLASSREGISTER_AddMember(scheduleBlockUpdateFromLoad, World::scheduleBlockUpdateFromLoad)
_CLASSREGISTER_AddMember(scheduleBlockUpdateWithPriority, World::scheduleBlockUpdateWithPriority)
_CLASSREGISTER_AddMember(sendQuittingDisconnectingPacket, World::sendQuittingDisconnectingPacket)
_CLASSREGISTER_AddMember_Override(setBlock, World::setBlock, bool, const BlockPos &, int, int, int)
_CLASSREGISTER_AddMember_Override(setBlock1, World::setBlock, bool, const BlockPos &, int)
_CLASSREGISTER_AddMember(setBlockMetadataWithNotify, World::setBlockMetadataWithNotify)
_CLASSREGISTER_AddMember(setBlockTileEntity, World::setBlockTileEntity)
_CLASSREGISTER_AddMember(setBlockToAir, World::setBlockToAir)
_CLASSREGISTER_AddMember(setEntityState, World::setEntityState)
_CLASSREGISTER_AddMember(setRandomSeed, World::setRandomSeed)
_CLASSREGISTER_AddMember_Override(setSpawnLocation, World::setSpawnLocation, void)
_CLASSREGISTER_AddMember_Override(setSpawnLocation1, World::setSpawnLocation, void, const Vector3i &)
_CLASSREGISTER_AddMember(setWorldTime, World::setWorldTime)
_CLASSREGISTER_AddMember(setWorldWeather, World::setWorldWeather)
_CLASSREGISTER_AddMember(spawnEntityInWorld, World::spawnEntityInWorld)
_CLASSREGISTER_AddMember(spawnParticle, World::spawnParticle)
_CLASSREGISTER_AddMember(tick, World::tick)
_CLASSREGISTER_AddMember(tickUpdates, World::tickUpdates)
_CLASSREGISTER_AddMember(unloadEntities, World::unloadEntities)
_CLASSREGISTER_AddMember(updateAllLightTypes, World::updateAllLightTypes)
_CLASSREGISTER_AddMember(updateAllPlayersSleepingFlag, World::updateAllPlayersSleepingFlag)
_CLASSREGISTER_AddMember(updateBlockLight, World::updateBlockLight)
_CLASSREGISTER_AddMember(updateComparatorOutputLevel, World::updateComparatorOutputLevel)
_CLASSREGISTER_AddMember(updateEntities, World::updateEntities)
_CLASSREGISTER_AddMember(updateEntity, World::updateEntity)
_CLASSREGISTER_AddMember(updateEntityWithOptionalForce, World::updateEntityWithOptionalForce)
_CLASSREGISTER_AddMember(updateLightByType, World::updateLightByType)
_CLASSREGISTER_AddMember(updateTileEntityChunkAndDoNothing, World::updateTileEntityChunkAndDoNothing)
_CLASSREGISTER_AddMember(spawnItemInWorld, World::spawnItemInWorld)
_CLASSREGISTER_AddMember(knockbackNoHarm, World::knockbackNoHarm)
_CLASSREGISTER_AddMember(setKnockbackNoHarm, World::setKnockbackNoHarm)
_CLASSREGISTER_AddMember(resetSignText, World::resetSignText)
_CLASSREGISTER_AddMember(addMerchant, World::addMerchant)
_CLASSREGISTER_AddMember(changePlayerActor, World::changePlayerActor)
_CLASSREGISTER_AddMember(restorePlayerActor, World::restorePlayerActor)
_CLASSREGISTER_AddMember(addGoodsGroupToShop, World::addGoodsGroupToShop)
_CLASSREGISTER_AddMember(addGoodsToShop, World::addGoodsToShop)
_CLASSREGISTER_AddMember(addRespawnGoodsToShop, World::addRespawnGoodsToShop)
_CLASSREGISTER_AddMember(addVehicle, World::addVehicle)
_CLASSREGISTER_AddMember(addRankNpc, World::addRankNpc)
_CLASSREGISTER_AddMember(resetVehiclePosition, World::resetVehiclePosition)
_CLASSREGISTER_AddMember(resetVehiclePositionAndYaw, World::resetVehiclePositionAndYaw)
_CLASSREGISTER_AddMember(hasPlayerByVehicle, World::hasPlayerByVehicle)
_CLASSREGISTER_AddMember(getPositionByEntityId, World::getPositionByEntityId)
_CLASSREGISTER_AddMember(addAircraft, World::addAircraft)
_CLASSREGISTER_AddMember(tryAllPlayerTakeAircraft, World::tryAllPlayerTakeAircraft)
_CLASSREGISTER_AddMember(tryAllPlayerOffAircraft, World::tryAllPlayerOffAircraft)
_CLASSREGISTER_AddMember(setPoisonCircleRange, World::setPoisonCircleRange)
_CLASSREGISTER_AddMember_Override(removeEntity, World::removeEntity, void, int)
_CLASSREGISTER_AddMember(addActorNpc, World::addActorNpc)
_CLASSREGISTER_AddMember(addSessionNpc, World::addSessionNpc)
_CLASSREGISTER_AddMember(setSessionNpcEffect, World::setSessionNpcEffect)
_CLASSREGISTER_AddMember(addCreature, World::addCreature)
_CLASSREGISTER_AddMember(addCreatureWithName, World::addCreatureWithName)
_CLASSREGISTER_AddMember(setCreatureTeam, World::setCreatureTeam)
_CLASSREGISTER_AddMember(addActorNpcWithName, World::addActorNpcWithName)
_CLASSREGISTER_AddMember(updateManorOwner, World::updateManorOwner)
_CLASSREGISTER_AddMember(addActorNpcWithJsonResult, World::addActorNpcWithJsonResult)
_CLASSREGISTER_AddMember(addActorNpcWithObstruct, World::addActorNpcWithObstruct)
_CLASSREGISTER_AddMember(addActorNpcWithNameAndObstruct, World::addActorNpcWithNameAndObstruct)
_CLASSREGISTER_AddMember(addRailCar, World::addRailCar)
_CLASSREGISTER_AddMember(addActorCannon, World::addActorCannon)
_CLASSREGISTER_AddMember(addBuildNpc, World::addBuildNpc)
_CLASSREGISTER_AddMember(addLandNpc, World::addLandNpc)
_CLASSREGISTER_AddMember(updateLandNpc, World::updateLandNpc)
_CLASSREGISTER_AddMember(addActorNpcWithCollided, World::addActorNpcWithCollided)
_CLASSREGISTER_AddMember(rangeCheckBlock, World::rangeCheckBlock)
_CLASSREGISTER_AddMember(rangeCheckBlockByEntityId, World::rangeCheckBlockByEntityId)
_END_REGISTER_CLASS()

// Register Class WorldChunkManager
_BEGIN_REGISTER_CLASS(WorldChunkManager)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(i64 , TERRAIN_TYPE )
_CLASSREGISTER_AddCtor(World * )
_CLASSREGISTER_AddMember(areBiomesViable, WorldChunkManager::areBiomesViable)
_CLASSREGISTER_AddMember(cleanupCache, WorldChunkManager::cleanupCache)
_CLASSREGISTER_AddMember(findBiomePosition, WorldChunkManager::findBiomePosition)
_CLASSREGISTER_AddMember_Override(getBiomeGenAt, WorldChunkManager::getBiomeGenAt,BiomeGenBase * ,int ,int )
_CLASSREGISTER_AddMember_Override(getBiomeGenAt1, WorldChunkManager::getBiomeGenAt,BiomeGenBase ** ,BiomeGenBase ** ,int ,int ,int ,int ,int ,bool )
_CLASSREGISTER_AddMember(getBiomesForGeneration, WorldChunkManager::getBiomesForGeneration)
_CLASSREGISTER_AddMember(getBiomesToSpawnIn, WorldChunkManager::getBiomesToSpawnIn)
_CLASSREGISTER_AddMember(getRainfall, WorldChunkManager::getRainfall)
_CLASSREGISTER_AddMember(getTemperatureAtHeight, WorldChunkManager::getTemperatureAtHeight)
_CLASSREGISTER_AddMember(getTemperatures, WorldChunkManager::getTemperatures)
_CLASSREGISTER_AddMember(loadBlockGeneratorData, WorldChunkManager::loadBlockGeneratorData)
_END_REGISTER_CLASS()




// Register Class WorldChunkManagerHell
_BEGIN_REGISTER_CLASS(WorldChunkManagerHell)
_CLASSREGISTER_AddBaseClass(WorldChunkManager)
_CLASSREGISTER_AddCtor(BiomeGenBase * , float , float)
_CLASSREGISTER_AddMember(areBiomesViable, WorldChunkManagerHell::areBiomesViable)
_CLASSREGISTER_AddMember(findBiomePosition, WorldChunkManagerHell::findBiomePosition)
_CLASSREGISTER_AddMember_Override(getBiomeGenAt, WorldChunkManagerHell::getBiomeGenAt,BiomeGenBase * ,int ,int )
_CLASSREGISTER_AddMember_Override(getBiomeGenAt1, WorldChunkManagerHell::getBiomeGenAt,BiomeGenBase ** ,BiomeGenBase ** ,int ,int ,int ,int ,int ,bool )
_CLASSREGISTER_AddMember(getBiomesForGeneration, WorldChunkManagerHell::getBiomesForGeneration)
_CLASSREGISTER_AddMember(getRainfall, WorldChunkManagerHell::getRainfall)
_CLASSREGISTER_AddMember(getTemperatures, WorldChunkManagerHell::getTemperatures)
_CLASSREGISTER_AddMember(loadBlockGeneratorData, WorldChunkManagerHell::loadBlockGeneratorData)
_END_REGISTER_CLASS()



// Register Class WorldInfo
_BEGIN_REGISTER_CLASS(WorldInfo)
_CLASSREGISTER_AddCtor()
_CLASSREGISTER_AddCtor(const String , const WorldSettings & )
_CLASSREGISTER_AddCtor(const WorldInfo & )
_CLASSREGISTER_AddMember(areCommandsAllowed, WorldInfo::areCommandsAllowed)
_CLASSREGISTER_AddMember(getGameType, WorldInfo::getGameType)
_CLASSREGISTER_AddMember(getGeneratorOptions, WorldInfo::getGeneratorOptions)
_CLASSREGISTER_AddMember(getLastTimePlayed, WorldInfo::getLastTimePlayed)
_CLASSREGISTER_AddMember(getMapId, WorldInfo::getMapId)
_CLASSREGISTER_AddMember(getRainTime, WorldInfo::getRainTime)
_CLASSREGISTER_AddMember(getSaveVersion, WorldInfo::getSaveVersion)
_CLASSREGISTER_AddMember(getSeed, WorldInfo::getSeed)
_CLASSREGISTER_AddMember(getSizeOnDisk, WorldInfo::getSizeOnDisk)
_CLASSREGISTER_AddMember(getSpawnX, WorldInfo::getSpawnX)
_CLASSREGISTER_AddMember(getSpawnY, WorldInfo::getSpawnY)
_CLASSREGISTER_AddMember(getSpawnZ, WorldInfo::getSpawnZ)
_CLASSREGISTER_AddMember(getTerrainType, WorldInfo::getTerrainType)
_CLASSREGISTER_AddMember(getThunderTime, WorldInfo::getThunderTime)
_CLASSREGISTER_AddMember(getVanillaDimension, WorldInfo::getVanillaDimension)
_CLASSREGISTER_AddMember(getWorldName, WorldInfo::getWorldName)
_CLASSREGISTER_AddMember(getWorldTime, WorldInfo::getWorldTime)
_CLASSREGISTER_AddMember(getWorldTotalTime, WorldInfo::getWorldTotalTime)
_CLASSREGISTER_AddMember(incrementTotalWorldTime, WorldInfo::incrementTotalWorldTime)
_CLASSREGISTER_AddMember(isHardcoreModeEnabled, WorldInfo::isHardcoreModeEnabled)
_CLASSREGISTER_AddMember(isInitialized, WorldInfo::isInitialized)
_CLASSREGISTER_AddMember(isMapFeaturesEnabled, WorldInfo::isMapFeaturesEnabled)
_CLASSREGISTER_AddMember(isRaining, WorldInfo::isRaining)
_CLASSREGISTER_AddMember(isThundering, WorldInfo::isThundering)
_CLASSREGISTER_AddMember(setGameType, WorldInfo::setGameType)
_CLASSREGISTER_AddMember(setRainTime, WorldInfo::setRainTime)
_CLASSREGISTER_AddMember(setRaining, WorldInfo::setRaining)
_CLASSREGISTER_AddMember(setSaveVersion, WorldInfo::setSaveVersion)
_CLASSREGISTER_AddMember(setServerInitialized, WorldInfo::setServerInitialized)
_CLASSREGISTER_AddMember(setSpawnPosition, WorldInfo::setSpawnPosition)
_CLASSREGISTER_AddMember(setSpawnX, WorldInfo::setSpawnX)
_CLASSREGISTER_AddMember(setSpawnY, WorldInfo::setSpawnY)
_CLASSREGISTER_AddMember(setSpawnZ, WorldInfo::setSpawnZ)
_CLASSREGISTER_AddMember(setTerrainType, WorldInfo::setTerrainType)
_CLASSREGISTER_AddMember(setThunderTime, WorldInfo::setThunderTime)
_CLASSREGISTER_AddMember(setThundering, WorldInfo::setThundering)
_CLASSREGISTER_AddMember(setWorldName, WorldInfo::setWorldName)
_CLASSREGISTER_AddMember(setWorldTime, WorldInfo::setWorldTime)
_END_REGISTER_CLASS()




// Register Class WorldProvider
_BEGIN_REGISTER_CLASS(WorldProvider)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddMember(calcSunriseSunsetColors, WorldProvider::calcSunriseSunsetColors)
_CLASSREGISTER_AddMember(calculateCelestialAngle, WorldProvider::calculateCelestialAngle)
_CLASSREGISTER_AddMember(canCoordinateBeSpawn, WorldProvider::canCoordinateBeSpawn)
_CLASSREGISTER_AddMember(canRespawnHere, WorldProvider::canRespawnHere)
_CLASSREGISTER_AddMember(createChunkGenerator, WorldProvider::createChunkGenerator)
_CLASSREGISTER_AddMember(doesXZShowFog, WorldProvider::doesXZShowFog)
_CLASSREGISTER_AddMember(generateLightBrightnessTable, WorldProvider::generateLightBrightnessTable)
_CLASSREGISTER_AddMember(getAverageGroundLevel, WorldProvider::getAverageGroundLevel)
_CLASSREGISTER_AddMember(getCloudHeight, WorldProvider::getCloudHeight)
_CLASSREGISTER_AddMember(getFogColor, WorldProvider::getFogColor)
_CLASSREGISTER_AddMember(getMoonPhase, WorldProvider::getMoonPhase)
_CLASSREGISTER_AddStaticMember(getProviderForDimension, WorldProvider::getProviderForDimension)
_CLASSREGISTER_AddMember(getVoidFogYFactor, WorldProvider::getVoidFogYFactor)
_CLASSREGISTER_AddMember(getWorldHasVoidParticles, WorldProvider::getWorldHasVoidParticles)
_CLASSREGISTER_AddMember(isSkyColored, WorldProvider::isSkyColored)
_CLASSREGISTER_AddMember(isSurfaceWorld, WorldProvider::isSurfaceWorld)
_CLASSREGISTER_AddMember(registerWorld, WorldProvider::registerWorld)
_CLASSREGISTER_AddMember(registerWorldChunkManager, WorldProvider::registerWorldChunkManager)
_END_REGISTER_CLASS()




// Register Class WorldProviderEnd
_BEGIN_REGISTER_CLASS(WorldProviderEnd)
_CLASSREGISTER_AddBaseClass(WorldProvider)
_CLASSREGISTER_AddMember(calcSunriseSunsetColors, WorldProviderEnd::calcSunriseSunsetColors)
_CLASSREGISTER_AddMember(calculateCelestialAngle, WorldProviderEnd::calculateCelestialAngle)
_CLASSREGISTER_AddMember(canCoordinateBeSpawn, WorldProviderEnd::canCoordinateBeSpawn)
_CLASSREGISTER_AddMember(canRespawnHere, WorldProviderEnd::canRespawnHere)
_CLASSREGISTER_AddMember(createChunkGenerator, WorldProviderEnd::createChunkGenerator)
_CLASSREGISTER_AddMember(doesXZShowFog, WorldProviderEnd::doesXZShowFog)
_CLASSREGISTER_AddMember(getAverageGroundLevel, WorldProviderEnd::getAverageGroundLevel)
_CLASSREGISTER_AddMember(getCloudHeight, WorldProviderEnd::getCloudHeight)
_CLASSREGISTER_AddMember(getDimensionName, WorldProviderEnd::getDimensionName)
_CLASSREGISTER_AddMember(getFogColor, WorldProviderEnd::getFogColor)
_CLASSREGISTER_AddMember(isSkyColored, WorldProviderEnd::isSkyColored)
_CLASSREGISTER_AddMember(isSurfaceWorld, WorldProviderEnd::isSurfaceWorld)
_CLASSREGISTER_AddMember(registerWorldChunkManager, WorldProviderEnd::registerWorldChunkManager)
_END_REGISTER_CLASS()




// Register Class WorldProviderHell
_BEGIN_REGISTER_CLASS(WorldProviderHell)
_CLASSREGISTER_AddBaseClass(WorldProvider)
_CLASSREGISTER_AddMember(calculateCelestialAngle, WorldProviderHell::calculateCelestialAngle)
_CLASSREGISTER_AddMember(canCoordinateBeSpawn, WorldProviderHell::canCoordinateBeSpawn)
_CLASSREGISTER_AddMember(canRespawnHere, WorldProviderHell::canRespawnHere)
_CLASSREGISTER_AddMember(createChunkGenerator, WorldProviderHell::createChunkGenerator)
_CLASSREGISTER_AddMember(doesXZShowFog, WorldProviderHell::doesXZShowFog)
_CLASSREGISTER_AddMember(generateLightBrightnessTable, WorldProviderHell::generateLightBrightnessTable)
_CLASSREGISTER_AddMember(getDimensionName, WorldProviderHell::getDimensionName)
_CLASSREGISTER_AddMember(getFogColor, WorldProviderHell::getFogColor)
_CLASSREGISTER_AddMember(isSurfaceWorld, WorldProviderHell::isSurfaceWorld)
_CLASSREGISTER_AddMember(registerWorldChunkManager, WorldProviderHell::registerWorldChunkManager)
_END_REGISTER_CLASS()




// Register Class WorldProviderSurface
_BEGIN_REGISTER_CLASS(WorldProviderSurface)
_CLASSREGISTER_AddBaseClass(WorldProvider)
_CLASSREGISTER_AddMember(createChunkGenerator, WorldProviderSurface::createChunkGenerator)
_CLASSREGISTER_AddMember(getDimensionName, WorldProviderSurface::getDimensionName)
_END_REGISTER_CLASS()




// Register Class WorldSettings
_BEGIN_REGISTER_CLASS(WorldSettings)
_CLASSREGISTER_AddBaseClass(ObjectAlloc)
_CLASSREGISTER_AddCtor(i64 , GAME_TYPE , bool , bool , TERRAIN_TYPE )
_CLASSREGISTER_AddCtor(const WorldInfo & )
_CLASSREGISTER_AddMember(areCommandsAllowed, WorldSettings::areCommandsAllowed)
_CLASSREGISTER_AddMember(enableBonusChest, WorldSettings::enableBonusChest)
_CLASSREGISTER_AddMember(enableCommands, WorldSettings::enableCommands)
_CLASSREGISTER_AddMember(func_82750_a, WorldSettings::func_82750_a)
_CLASSREGISTER_AddMember(getGameType, WorldSettings::getGameType)
_CLASSREGISTER_AddMember(getGenerateOptions, WorldSettings::getGenerateOptions)
_CLASSREGISTER_AddMember(getHardcoreEnabled, WorldSettings::getHardcoreEnabled)
_CLASSREGISTER_AddMember(getSeed, WorldSettings::getSeed)
_CLASSREGISTER_AddMember(getTerrainType, WorldSettings::getTerrainType)
_CLASSREGISTER_AddMember(isBonusChestEnabled, WorldSettings::isBonusChestEnabled)
_CLASSREGISTER_AddMember(isMapFeaturesEnabled, WorldSettings::isMapFeaturesEnabled)
_END_REGISTER_CLASS()




